---
apiVersion: v1
kind: Service
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: data-service-{{ .DRONE_SOURCE_BRANCH }}
  labels:
    name: data-service-{{ .DRONE_SOURCE_BRANCH }}
    role: service-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: data-service
  labels:
    name: data-service
    role: service
  {{ end }}
spec:
  selector:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    name: data-service-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    name: data-service
    {{ end }}
  type: ClusterIP
  ports:
  - name: http
    port: 10080
  - name: https-lookup
    port: 10443
  - name: https-api
    port: 10445
