---
apiVersion: v1
kind: Service
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: dataservice-{{ .DRONE_SOURCE_BRANCH }}
  labels:
    name: dataservice-{{ .DRONE_SOURCE_BRANCH }}
    role: service-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: dataservice
  labels:
    name: dataservice
    role: service
  {{ end }}
spec:
  selector:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    name: data-service-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    name: data-service
    {{ end }}
  ports:
  - name: http
    port: 10080
  - name: https
    port: 10443
