'use strict'

const ukCitiesAndTowns = [
{value:"Aberaeron",label:"Aberaeron"},
{value:"Abercarn",label:"Abercarn"},
{value:"Aberchirder",label:"Aberchirder"},
{value:"Abercynon",label:"Abercynon"},
{value:"Aberdare / Aberdâr",label:"Aberdare / Aberdâr"},
{value:"Aberdeen",label:"Aberdeen"},
{value:"Aberfeldy",label:"Aberfeldy"},
{value:"Abergavenny / Y Fenni",label:"Abergavenny / Y Fenni"},
{value:"Abergele",label:"Abergele"},
{value:"Abersychan",label:"Abersychan"},
{value:"Abertillery / Abertyleri",label:"Abertillery / Abertyleri"},
{value:"Aberystwyth",label:"Aberystwyth"},
{value:"Abingdon-on-Thames",label:"Abingdon-on-Thames"},
{value:"Accrington",label:"Accrington"},
{value:"Acton",label:"Acton"},
{value:"Addlestone",label:"Addlestone"},
{value:"Adlington",label:"Adlington"},
{value:"Adwick le Street",label:"Adwick le Street"},
{value:"Airdrie",label:"Airdrie"},
{value:"Alcester",label:"Alcester"},
{value:"Aldeburgh",label:"Aldeburgh"},
{value:"Aldershot",label:"Aldershot"},
{value:"Aldridge",label:"Aldridge"},
{value:"Alexandria",label:"Alexandria"},
{value:"Alford",label:"Alford"},
{value:"Alfreton",label:"Alfreton"},
{value:"Alloa",label:"Alloa"},
{value:"Alness",label:"Alness"},
{value:"Alnwick",label:"Alnwick"},
{value:"Alsager",label:"Alsager"},
{value:"Alston",label:"Alston"},
{value:"Alton",label:"Alton"},
{value:"Altrincham",label:"Altrincham"},
{value:"Alva",label:"Alva"},
{value:"Alyth",label:"Alyth"},
{value:"Amble",label:"Amble"},
{value:"Ambleside",label:"Ambleside"},
{value:"Amersham",label:"Amersham"},
{value:"Amesbury",label:"Amesbury"},
{value:"Amlwch",label:"Amlwch"},
{value:"Ammanford / Rhydaman",label:"Ammanford / Rhydaman"},
{value:"Ampthill",label:"Ampthill"},
{value:"Andover",label:"Andover"},
{value:"Annan",label:"Annan"},
{value:"Annfield Plain",label:"Annfield Plain"},
{value:"Anstruther",label:"Anstruther"},
{value:"Antrim",label:"Antrim"},
{value:"Appleby-in-Westmorland",label:"Appleby-in-Westmorland"},
{value:"Arbroath",label:"Arbroath"},
{value:"Ardrossan",label:"Ardrossan"},
{value:"Armadale",label:"Armadale"},
{value:"Armagh",label:"Armagh"},
{value:"Arnold",label:"Arnold"},
{value:"Arundel",label:"Arundel"},
{value:"Ashbourne",label:"Ashbourne"},
{value:"Ashburton",label:"Ashburton"},
{value:"Ashby-de-la-Zouch",label:"Ashby-de-la-Zouch"},
{value:"Ashford",label:"Ashford"},
{value:"Ashford",label:"Ashford"},
{value:"Ashington",label:"Ashington"},
{value:"Ashton-in-Makerfield",label:"Ashton-in-Makerfield"},
{value:"Ashton-under-Lyne",label:"Ashton-under-Lyne"},
{value:"Aspatria",label:"Aspatria"},
{value:"Atherstone",label:"Atherstone"},
{value:"Atherton",label:"Atherton"},
{value:"Attleborough",label:"Attleborough"},
{value:"Auchterarder",label:"Auchterarder"},
{value:"Auchtermuchty",label:"Auchtermuchty"},
{value:"Aviemore",label:"Aviemore"},
{value:"Axbridge",label:"Axbridge"},
{value:"Axminster",label:"Axminster"},
{value:"Aylesbury",label:"Aylesbury"},
{value:"Aylsham",label:"Aylsham"},
{value:"Ayr",label:"Ayr"},
{value:"Bacup",label:"Bacup"},
{value:"Baildon",label:"Baildon"},
{value:"Bakewell",label:"Bakewell"},
{value:"Baldock",label:"Baldock"},
{value:"Ballater",label:"Ballater"},
{value:"Ballycastle",label:"Ballycastle"},
{value:"Ballyclare",label:"Ballyclare"},
{value:"Ballymena",label:"Ballymena"},
{value:"Ballymoney",label:"Ballymoney"},
{value:"Ballynahinch",label:"Ballynahinch"},
{value:"Bamber Bridge",label:"Bamber Bridge"},
{value:"Banbridge",label:"Banbridge"},
{value:"Banbury",label:"Banbury"},
{value:"Banchory",label:"Banchory"},
{value:"Banff",label:"Banff"},
{value:"Bangor",label:"Bangor"},
{value:"Bangor",label:"Bangor"},
{value:"Banstead",label:"Banstead"},
{value:"Bargod / Bargoed",label:"Bargod / Bargoed"},
{value:"Barmouth / Abermaw",label:"Barmouth / Abermaw"},
{value:"Barnard Castle",label:"Barnard Castle"},
{value:"Barnoldswick",label:"Barnoldswick"},
{value:"Barnsley",label:"Barnsley"},
{value:"Barnstaple",label:"Barnstaple"},
{value:"Barrhead",label:"Barrhead"},
{value:"Barrowford",label:"Barrowford"},
{value:"Barrow-in-Furness",label:"Barrow-in-Furness"},
{value:"Barry / Barri",label:"Barry / Barri"},
{value:"Barton-upon-Humber",label:"Barton-upon-Humber"},
{value:"Basildon",label:"Basildon"},
{value:"Basingstoke",label:"Basingstoke"},
{value:"Bath",label:"Bath"},
{value:"Bathgate",label:"Bathgate"},
{value:"Batley",label:"Batley"},
{value:"Battle",label:"Battle"},
{value:"Bawtry",label:"Bawtry"},
{value:"Beaconsfield",label:"Beaconsfield"},
{value:"Beaminster",label:"Beaminster"},
{value:"Bearsden",label:"Bearsden"},
{value:"Beaumaris",label:"Beaumaris"},
{value:"Bebington",label:"Bebington"},
{value:"Beccles",label:"Beccles"},
{value:"Bedale",label:"Bedale"},
{value:"Bedford",label:"Bedford"},
{value:"Bedlington",label:"Bedlington"},
{value:"Bedworth",label:"Bedworth"},
{value:"Beeston",label:"Beeston"},
{value:"Belfast",label:"Belfast"},
{value:"Bellshill",label:"Bellshill"},
{value:"Belper",label:"Belper"},
{value:"Bentley",label:"Bentley"},
{value:"Berkhamsted",label:"Berkhamsted"},
{value:"Berwick-upon-Tweed",label:"Berwick-upon-Tweed"},
{value:"Bethesda",label:"Bethesda"},
{value:"Betws-y-Coed",label:"Betws-y-Coed"},
{value:"Beverley",label:"Beverley"},
{value:"Bewdley",label:"Bewdley"},
{value:"Bexhill",label:"Bexhill"},
{value:"Bicester",label:"Bicester"},
{value:"Biddulph",label:"Biddulph"},
{value:"Bideford",label:"Bideford"},
{value:"Biggar",label:"Biggar"},
{value:"Biggleswade",label:"Biggleswade"},
{value:"Billericay",label:"Billericay"},
{value:"Billinge",label:"Billinge"},
{value:"Billingham",label:"Billingham"},
{value:"Bilston",label:"Bilston"},
{value:"Bingham",label:"Bingham"},
{value:"Bingley",label:"Bingley"},
{value:"Birkenhead",label:"Birkenhead"},
{value:"Birmingham",label:"Birmingham"},
{value:"Bishop Auckland",label:"Bishop Auckland"},
{value:"Bishopbriggs",label:"Bishopbriggs"},
{value:"Bishop's Castle",label:"Bishop's Castle"},
{value:"Bishop's Stortford",label:"Bishop's Stortford"},
{value:"Bishop's Waltham",label:"Bishop's Waltham"},
{value:"Blackburn",label:"Blackburn"},
{value:"Blackburn",label:"Blackburn"},
{value:"Blackburn",label:"Blackburn"},
{value:"Blackheath",label:"Blackheath"},
{value:"Blackpool",label:"Blackpool"},
{value:"Blackwater",label:"Blackwater"},
{value:"Blackwood / Y Coed Duon",label:"Blackwood / Y Coed Duon"},
{value:"Blaenau Ffestiniog",label:"Blaenau Ffestiniog"},
{value:"Blaenavon",label:"Blaenavon"},
{value:"Blaina / Y Blaenau",label:"Blaina / Y Blaenau"},
{value:"Blairgowrie and Rattray",label:"Blairgowrie and Rattray"},
{value:"Blandford Forum",label:"Blandford Forum"},
{value:"Blaydon",label:"Blaydon"},
{value:"Bletchley",label:"Bletchley"},
{value:"Bloxwich",label:"Bloxwich"},
{value:"Blyth",label:"Blyth"},
{value:"Bodmin",label:"Bodmin"},
{value:"Bognor Regis",label:"Bognor Regis"},
{value:"Bollington",label:"Bollington"},
{value:"Bolsover",label:"Bolsover"},
{value:"Bolton",label:"Bolton"},
{value:"Bolton upon Dearne",label:"Bolton upon Dearne"},
{value:"Bo'ness",label:"Bo'ness"},
{value:"Bonnyrigg",label:"Bonnyrigg"},
{value:"Bootle",label:"Bootle"},
{value:"Bordon",label:"Bordon"},
{value:"Borehamwood",label:"Borehamwood"},
{value:"Boroughbridge",label:"Boroughbridge"},
{value:"Boston",label:"Boston"},
{value:"Bourne",label:"Bourne"},
{value:"Bournemouth",label:"Bournemouth"},
{value:"Bovey Tracey",label:"Bovey Tracey"},
{value:"Bowness-on-Windermere",label:"Bowness-on-Windermere"},
{value:"Brackley",label:"Brackley"},
{value:"Bracknell",label:"Bracknell"},
{value:"Bradford",label:"Bradford"},
{value:"Bradford-on-Avon",label:"Bradford-on-Avon"},
{value:"Brading",label:"Brading"},
{value:"Bradley Stoke",label:"Bradley Stoke"},
{value:"Braintree",label:"Braintree"},
{value:"Bramhall",label:"Bramhall"},
{value:"Brampton",label:"Brampton"},
{value:"Brandon",label:"Brandon"},
{value:"Brechin",label:"Brechin"},
{value:"Brecon / Aberhonddu",label:"Brecon / Aberhonddu"},
{value:"Brentwood",label:"Brentwood"},
{value:"Bridgend / Pen-y-bont ar Ogwr",label:"Bridgend / Pen-y-bont ar Ogwr"},
{value:"Bridge of Allan",label:"Bridge of Allan"},
{value:"Bridgnorth",label:"Bridgnorth"},
{value:"Bridgwater",label:"Bridgwater"},
{value:"Bridlington",label:"Bridlington"},
{value:"Bridport",label:"Bridport"},
{value:"Brierfield",label:"Brierfield"},
{value:"Brierley Hill",label:"Brierley Hill"},
{value:"Brigg",label:"Brigg"},
{value:"Brighouse",label:"Brighouse"},
{value:"Brightlingsea",label:"Brightlingsea"},
{value:"Brighton and Hove",label:"Brighton and Hove"},
{value:"Bristol",label:"Bristol"},
{value:"Brixham",label:"Brixham"},
{value:"Broadstairs",label:"Broadstairs"},
{value:"Bromsgrove",label:"Bromsgrove"},
{value:"Bromyard",label:"Bromyard"},
{value:"Broseley",label:"Broseley"},
{value:"Brotton",label:"Brotton"},
{value:"Broughton in Furness",label:"Broughton in Furness"},
{value:"Broughty Ferry",label:"Broughty Ferry"},
{value:"Brownhills",label:"Brownhills"},
{value:"Broxburn",label:"Broxburn"},
{value:"Bruton",label:"Bruton"},
{value:"Brynmawr / Bryn-Mawr",label:"Brynmawr / Bryn-Mawr"},
{value:"Buckfastleigh",label:"Buckfastleigh"},
{value:"Buckhaven",label:"Buckhaven"},
{value:"Buckie",label:"Buckie"},
{value:"Buckingham",label:"Buckingham"},
{value:"Buckley / Bwcle",label:"Buckley / Bwcle"},
{value:"Bude",label:"Bude"},
{value:"Budleigh Salterton",label:"Budleigh Salterton"},
{value:"Builth Wells / Llanfair-ym-Muallt",label:"Builth Wells / Llanfair-ym-Muallt"},
{value:"Bungay",label:"Bungay"},
{value:"Buntingford",label:"Buntingford"},
{value:"Burford",label:"Burford"},
{value:"Burgess Hill",label:"Burgess Hill"},
{value:"Burghead",label:"Burghead"},
{value:"Burnham-on-Crouch",label:"Burnham-on-Crouch"},
{value:"Burnham-on-Sea",label:"Burnham-on-Sea"},
{value:"Burnley",label:"Burnley"},
{value:"Burntisland",label:"Burntisland"},
{value:"Burntwood",label:"Burntwood"},
{value:"Burry Port / Porth Tywyn",label:"Burry Port / Porth Tywyn"},
{value:"Burton Latimer",label:"Burton Latimer"},
{value:"Burton upon Trent",label:"Burton upon Trent"},
{value:"Bury",label:"Bury"},
{value:"Bury St Edmunds",label:"Bury St Edmunds"},
{value:"Bushey",label:"Bushey"},
{value:"Buxton",label:"Buxton"},
{value:"Caerleon / Caerllion",label:"Caerleon / Caerllion"},
{value:"Caernarfon",label:"Caernarfon"},
{value:"Caerphilly / Caerffili",label:"Caerphilly / Caerffili"},
{value:"Caerwys",label:"Caerwys"},
{value:"Caister-on-Sea",label:"Caister-on-Sea"},
{value:"Caldicot / Cil-y-coed",label:"Caldicot / Cil-y-coed"},
{value:"Callander",label:"Callander"},
{value:"Callington",label:"Callington"},
{value:"Calne",label:"Calne"},
{value:"Camberley",label:"Camberley"},
{value:"Camborne",label:"Camborne"},
{value:"Cambridge",label:"Cambridge"},
{value:"Camelford",label:"Camelford"},
{value:"Campbeltown / Ceann Loch Chille Chiarain",label:"Campbeltown / Ceann Loch Chille Chiarain"},
{value:"Cannock",label:"Cannock"},
{value:"Canterbury",label:"Canterbury"},
{value:"Canvey Island",label:"Canvey Island"},
{value:"Cardiff / Caerdydd",label:"Cardiff / Caerdydd"},
{value:"Cardigan / Aberteifi",label:"Cardigan / Aberteifi"},
{value:"Carlisle",label:"Carlisle"},
{value:"Carluke",label:"Carluke"},
{value:"Carmarthen / Caerfyrddin",label:"Carmarthen / Caerfyrddin"},
{value:"Carnforth",label:"Carnforth"},
{value:"Carnoustie",label:"Carnoustie"},
{value:"Carrickfergus",label:"Carrickfergus"},
{value:"Carryduff",label:"Carryduff"},
{value:"Carterton",label:"Carterton"},
{value:"Castle Cary",label:"Castle Cary"},
{value:"Castle Douglas",label:"Castle Douglas"},
{value:"Castleford",label:"Castleford"},
{value:"Castletown",label:"Castletown"},
{value:"Caterham",label:"Caterham"},
{value:"Chadderton",label:"Chadderton"},
{value:"Chagford",label:"Chagford"},
{value:"Chapel-en-le-Frith",label:"Chapel-en-le-Frith"},
{value:"Chard",label:"Chard"},
{value:"Charlbury",label:"Charlbury"},
{value:"Charlestown of Aberlour",label:"Charlestown of Aberlour"},
{value:"Chatham",label:"Chatham"},
{value:"Chatteris",label:"Chatteris"},
{value:"Cheadle",label:"Cheadle"},
{value:"Cheadle",label:"Cheadle"},
{value:"Cheadle Hulme",label:"Cheadle Hulme"},
{value:"Chelmsford",label:"Chelmsford"},
{value:"Cheltenham",label:"Cheltenham"},
{value:"Chepstow / Cas-Gwent",label:"Chepstow / Cas-Gwent"},
{value:"Chertsey",label:"Chertsey"},
{value:"Chesham",label:"Chesham"},
{value:"Cheshunt",label:"Cheshunt"},
{value:"Chester",label:"Chester"},
{value:"Chesterfield",label:"Chesterfield"},
{value:"Chester-le-Street",label:"Chester-le-Street"},
{value:"Chichester",label:"Chichester"},
{value:"Chickerell",label:"Chickerell"},
{value:"Chigwell",label:"Chigwell"},
{value:"Chippenham",label:"Chippenham"},
{value:"Chipping Campden",label:"Chipping Campden"},
{value:"Chipping Norton",label:"Chipping Norton"},
{value:"Chipping Ongar",label:"Chipping Ongar"},
{value:"Chipping Sodbury",label:"Chipping Sodbury"},
{value:"Chirk / Y Waun",label:"Chirk / Y Waun"},
{value:"Chorley",label:"Chorley"},
{value:"Chorleywood",label:"Chorleywood"},
{value:"Christchurch",label:"Christchurch"},
{value:"Chudleigh",label:"Chudleigh"},
{value:"Church",label:"Church"},
{value:"Church Stretton",label:"Church Stretton"},
{value:"Cinderford",label:"Cinderford"},
{value:"Cirencester",label:"Cirencester"},
{value:"Clackmannan",label:"Clackmannan"},
{value:"Clacton-on-Sea",label:"Clacton-on-Sea"},
{value:"Clare",label:"Clare"},
{value:"Clay Cross",label:"Clay Cross"},
{value:"Clayton-le-Moors",label:"Clayton-le-Moors"},
{value:"Cleator Moor",label:"Cleator Moor"},
{value:"Cleckheaton",label:"Cleckheaton"},
{value:"Cleethorpes",label:"Cleethorpes"},
{value:"Cleobury Mortimer",label:"Cleobury Mortimer"},
{value:"Clevedon",label:"Clevedon"},
{value:"Cleveleys",label:"Cleveleys"},
{value:"Clitheroe",label:"Clitheroe"},
{value:"Clydebank",label:"Clydebank"},
{value:"Coalisland",label:"Coalisland"},
{value:"Coalville",label:"Coalville"},
{value:"Coatbridge",label:"Coatbridge"},
{value:"Cockenzie and Port Seton",label:"Cockenzie and Port Seton"},
{value:"Cockermouth",label:"Cockermouth"},
{value:"Coggeshall",label:"Coggeshall"},
{value:"Colchester",label:"Colchester"},
{value:"Coldstream",label:"Coldstream"},
{value:"Coleford",label:"Coleford"},
{value:"Coleraine",label:"Coleraine"},
{value:"Coleshill",label:"Coleshill"},
{value:"Colne",label:"Colne"},
{value:"Colwyn Bay / Bae Colwyn",label:"Colwyn Bay / Bae Colwyn"},
{value:"Colyton",label:"Colyton"},
{value:"Comber",label:"Comber"},
{value:"Congleton",label:"Congleton"},
{value:"Conisbrough",label:"Conisbrough"},
{value:"Connah's Quay / Cei Connah",label:"Connah's Quay / Cei Connah"},
{value:"Consett",label:"Consett"},
{value:"Conwy",label:"Conwy"},
{value:"Cookstown",label:"Cookstown"},
{value:"Corbridge",label:"Corbridge"},
{value:"Corby",label:"Corby"},
{value:"Corsham",label:"Corsham"},
{value:"Coseley",label:"Coseley"},
{value:"Cotgrave",label:"Cotgrave"},
{value:"Cottingham",label:"Cottingham"},
{value:"Coupar Angus",label:"Coupar Angus"},
{value:"Coventry",label:"Coventry"},
{value:"Cowbridge / Y Bont-Faen",label:"Cowbridge / Y Bont-Faen"},
{value:"Cowdenbeath",label:"Cowdenbeath"},
{value:"Cowes",label:"Cowes"},
{value:"Craigavon",label:"Craigavon"},
{value:"Crail",label:"Crail"},
{value:"Cramlington",label:"Cramlington"},
{value:"Craven Arms",label:"Craven Arms"},
{value:"Crawley",label:"Crawley"},
{value:"Crediton",label:"Crediton"},
{value:"Crewe",label:"Crewe"},
{value:"Crewkerne",label:"Crewkerne"},
{value:"Criccieth / Cricieth",label:"Criccieth / Cricieth"},
{value:"Crickhowell / Crughywel",label:"Crickhowell / Crughywel"},
{value:"Cricklade",label:"Cricklade"},
{value:"Crieff",label:"Crieff"},
{value:"Cromarty",label:"Cromarty"},
{value:"Cromer",label:"Cromer"},
{value:"Crook",label:"Crook"},
{value:"Crosby",label:"Crosby"},
{value:"Crowborough",label:"Crowborough"},
{value:"Crowland",label:"Crowland"},
{value:"Crowle",label:"Crowle"},
{value:"Crowthorne",label:"Crowthorne"},
{value:"Cuckfield",label:"Cuckfield"},
{value:"Cullen",label:"Cullen"},
{value:"Cullompton",label:"Cullompton"},
{value:"Culross",label:"Culross"},
{value:"Cumbernauld",label:"Cumbernauld"},
{value:"Cumnock",label:"Cumnock"},
{value:"Cupar",label:"Cupar"},
{value:"Cwmbrân",label:"Cwmbrân"},
{value:"Dalbeattie",label:"Dalbeattie"},
{value:"Dalkeith",label:"Dalkeith"},
{value:"Dalton-in-Furness",label:"Dalton-in-Furness"},
{value:"Darlaston",label:"Darlaston"},
{value:"Darley Dale",label:"Darley Dale"},
{value:"Darlington",label:"Darlington"},
{value:"Dartford",label:"Dartford"},
{value:"Dartmouth",label:"Dartmouth"},
{value:"Darvel",label:"Darvel"},
{value:"Darwen",label:"Darwen"},
{value:"Daventry",label:"Daventry"},
{value:"Dawlish",label:"Dawlish"},
{value:"Deal",label:"Deal"},
{value:"Denbigh / Dinbych",label:"Denbigh / Dinbych"},
{value:"Denny",label:"Denny"},
{value:"Denton",label:"Denton"},
{value:"Derby",label:"Derby"},
{value:"Dereham",label:"Dereham"},
{value:"Derry / Londonderry",label:"Derry / Londonderry"},
{value:"Desborough",label:"Desborough"},
{value:"Devizes",label:"Devizes"},
{value:"Dewsbury",label:"Dewsbury"},
{value:"Didcot",label:"Didcot"},
{value:"Dingwall",label:"Dingwall"},
{value:"Dinnington",label:"Dinnington"},
{value:"Diss",label:"Diss"},
{value:"Dolgellau",label:"Dolgellau"},
{value:"Dollar",label:"Dollar"},
{value:"Donaghadee",label:"Donaghadee"},
{value:"Doncaster",label:"Doncaster"},
{value:"Dorchester",label:"Dorchester"},
{value:"Dorking",label:"Dorking"},
{value:"Dornoch",label:"Dornoch"},
{value:"Douglas",label:"Douglas"},
{value:"Doune",label:"Doune"},
{value:"Dover",label:"Dover"},
{value:"Downham Market",label:"Downham Market"},
{value:"Downpatrick",label:"Downpatrick"},
{value:"Driffield",label:"Driffield"},
{value:"Droitwich Spa",label:"Droitwich Spa"},
{value:"Dromore ",label:"Dromore "},
{value:"Dronfield",label:"Dronfield"},
{value:"Droylsden",label:"Droylsden"},
{value:"Dudley",label:"Dudley"},
{value:"Dufftown",label:"Dufftown"},
{value:"Dukinfield",label:"Dukinfield"},
{value:"Dulverton",label:"Dulverton"},
{value:"Dumbarton",label:"Dumbarton"},
{value:"Dumfries",label:"Dumfries"},
{value:"Dunbar",label:"Dunbar"},
{value:"Dunblane",label:"Dunblane"},
{value:"Dundee",label:"Dundee"},
{value:"Dundonald",label:"Dundonald"},
{value:"Dunfermline",label:"Dunfermline"},
{value:"Dungannon",label:"Dungannon"},
{value:"Dunmurry",label:"Dunmurry"},
{value:"Dunoon / Dùn Obhainn",label:"Dunoon / Dùn Obhainn"},
{value:"Duns",label:"Duns"},
{value:"Dunstable",label:"Dunstable"},
{value:"Durham",label:"Durham"},
{value:"Dursley",label:"Dursley"},
{value:"Earby",label:"Earby"},
{value:"Earl Shilton",label:"Earl Shilton"},
{value:"Easingwold",label:"Easingwold"},
{value:"Eastbourne",label:"Eastbourne"},
{value:"East Cowes",label:"East Cowes"},
{value:"East Grinstead",label:"East Grinstead"},
{value:"East Kilbride",label:"East Kilbride"},
{value:"Eastleigh",label:"Eastleigh"},
{value:"East Linton",label:"East Linton"},
{value:"Eastwood",label:"Eastwood"},
{value:"Ebbw Vale / Glyn Ebwy",label:"Ebbw Vale / Glyn Ebwy"},
{value:"Eccles",label:"Eccles"},
{value:"Eccleshall",label:"Eccleshall"},
{value:"Edenbridge",label:"Edenbridge"},
{value:"Edinburgh",label:"Edinburgh"},
{value:"Egham",label:"Egham"},
{value:"Egremont",label:"Egremont"},
{value:"Elgin",label:"Elgin"},
{value:"Elland",label:"Elland"},
{value:"Ellesmere",label:"Ellesmere"},
{value:"Ellesmere Port",label:"Ellesmere Port"},
{value:"Ellon",label:"Ellon"},
{value:"Ely",label:"Ely"},
{value:"Emsworth",label:"Emsworth"},
{value:"Enniskillen",label:"Enniskillen"},
{value:"Epping",label:"Epping"},
{value:"Epsom",label:"Epsom"},
{value:"Epworth",label:"Epworth"},
{value:"Erskine",label:"Erskine"},
{value:"Esher",label:"Esher"},
{value:"Eton",label:"Eton"},
{value:"Evesham",label:"Evesham"},
{value:"Ewell",label:"Ewell"},
{value:"Exeter",label:"Exeter"},
{value:"Exmouth",label:"Exmouth"},
{value:"Eye",label:"Eye"},
{value:"Eyemouth",label:"Eyemouth"},
{value:"Failsworth",label:"Failsworth"},
{value:"Fairford",label:"Fairford"},
{value:"Fakenham",label:"Fakenham"},
{value:"Falkirk",label:"Falkirk"},
{value:"Falkland",label:"Falkland"},
{value:"Falmouth",label:"Falmouth"},
{value:"Fareham",label:"Fareham"},
{value:"Faringdon",label:"Faringdon"},
{value:"Farnborough",label:"Farnborough"},
{value:"Farnham",label:"Farnham"},
{value:"Farnworth",label:"Farnworth"},
{value:"Faversham",label:"Faversham"},
{value:"Fazeley",label:"Fazeley"},
{value:"Featherstone",label:"Featherstone"},
{value:"Felixstowe",label:"Felixstowe"},
{value:"Ferndale",label:"Ferndale"},
{value:"Ferndown",label:"Ferndown"},
{value:"Ferryhill",label:"Ferryhill"},
{value:"Filey",label:"Filey"},
{value:"Filton",label:"Filton"},
{value:"Findochty",label:"Findochty"},
{value:"Fishguard / Abergwaun",label:"Fishguard / Abergwaun"},
{value:"Fleet",label:"Fleet"},
{value:"Fleetwood",label:"Fleetwood"},
{value:"Flint / Y Fflint",label:"Flint / Y Fflint"},
{value:"Flitwick",label:"Flitwick"},
{value:"Folkestone",label:"Folkestone"},
{value:"Fordingbridge",label:"Fordingbridge"},
{value:"Forfar",label:"Forfar"},
{value:"Formby",label:"Formby"},
{value:"Forres",label:"Forres"},
{value:"Fortrose",label:"Fortrose"},
{value:"Fortuneswell",label:"Fortuneswell"},
{value:"Fort William / An Gearasdan",label:"Fort William / An Gearasdan"},
{value:"Fowey",label:"Fowey"},
{value:"Framlingham",label:"Framlingham"},
{value:"Fraserburgh",label:"Fraserburgh"},
{value:"Freckleton",label:"Freckleton"},
{value:"Frimley",label:"Frimley"},
{value:"Frinton-on-Sea",label:"Frinton-on-Sea"},
{value:"Frodsham",label:"Frodsham"},
{value:"Frome",label:"Frome"},
{value:"Fulwood",label:"Fulwood"},
{value:"Gainsborough",label:"Gainsborough"},
{value:"Galashiels",label:"Galashiels"},
{value:"Galston",label:"Galston"},
{value:"Garforth",label:"Garforth"},
{value:"Garstang",label:"Garstang"},
{value:"Gatehouse of Fleet",label:"Gatehouse of Fleet"},
{value:"Gateshead",label:"Gateshead"},
{value:"Gatley",label:"Gatley"},
{value:"Gerrards Cross",label:"Gerrards Cross"},
{value:"Gillingham",label:"Gillingham"},
{value:"Gillingham",label:"Gillingham"},
{value:"Girvan",label:"Girvan"},
{value:"Glasgow",label:"Glasgow"},
{value:"Glastonbury",label:"Glastonbury"},
{value:"Glenrothes",label:"Glenrothes"},
{value:"Glossop",label:"Glossop"},
{value:"Gloucester",label:"Gloucester"},
{value:"Glyn-neath / Glyn-nedd",label:"Glyn-neath / Glyn-nedd"},
{value:"Godalming",label:"Godalming"},
{value:"Godmanchester",label:"Godmanchester"},
{value:"Golborne",label:"Golborne"},
{value:"Goldthorpe",label:"Goldthorpe"},
{value:"Goodwick / Wdig",label:"Goodwick / Wdig"},
{value:"Goole",label:"Goole"},
{value:"Gorleston-on-Sea",label:"Gorleston-on-Sea"},
{value:"Gorseinon",label:"Gorseinon"},
{value:"Gosport",label:"Gosport"},
{value:"Gourock",label:"Gourock"},
{value:"Grangemouth",label:"Grangemouth"},
{value:"Grange-over-Sands",label:"Grange-over-Sands"},
{value:"Grantham",label:"Grantham"},
{value:"Grantown-on-Spey",label:"Grantown-on-Spey"},
{value:"Gravesend",label:"Gravesend"},
{value:"Grays",label:"Grays"},
{value:"Great Dunmow",label:"Great Dunmow"},
{value:"Great Harwood",label:"Great Harwood"},
{value:"Great Malvern",label:"Great Malvern"},
{value:"Great Torrington",label:"Great Torrington"},
{value:"Great Yarmouth",label:"Great Yarmouth"},
{value:"Greenock",label:"Greenock"},
{value:"Grimsby",label:"Grimsby"},
{value:"Guildford",label:"Guildford"},
{value:"Guisborough",label:"Guisborough"},
{value:"Guiseley",label:"Guiseley"},
{value:"Haddington",label:"Haddington"},
{value:"Hadleigh",label:"Hadleigh"},
{value:"Hailsham",label:"Hailsham"},
{value:"Hale",label:"Hale"},
{value:"Halesowen",label:"Halesowen"},
{value:"Halesworth",label:"Halesworth"},
{value:"Halifax",label:"Halifax"},
{value:"Halstead",label:"Halstead"},
{value:"Haltwhistle",label:"Haltwhistle"},
{value:"Hamilton",label:"Hamilton"},
{value:"Harlech",label:"Harlech"},
{value:"Harleston",label:"Harleston"},
{value:"Harlow",label:"Harlow"},
{value:"Harpenden",label:"Harpenden"},
{value:"Harrogate",label:"Harrogate"},
{value:"Hartlepool",label:"Hartlepool"},
{value:"Harwich",label:"Harwich"},
{value:"Haslemere",label:"Haslemere"},
{value:"Haslingden",label:"Haslingden"},
{value:"Hastings",label:"Hastings"},
{value:"Hatfield",label:"Hatfield"},
{value:"Havant",label:"Havant"},
{value:"Haverfordwest / Hwlffordd",label:"Haverfordwest / Hwlffordd"},
{value:"Haverhill",label:"Haverhill"},
{value:"Hawick",label:"Hawick"},
{value:"Haxby",label:"Haxby"},
{value:"Haydock",label:"Haydock"},
{value:"Hayle",label:"Hayle"},
{value:"Hay-on-Wye / Y Gelli Gandryll",label:"Hay-on-Wye / Y Gelli Gandryll"},
{value:"Haywards Heath",label:"Haywards Heath"},
{value:"Hazel Grove",label:"Hazel Grove"},
{value:"Heanor",label:"Heanor"},
{value:"Heathfield",label:"Heathfield"},
{value:"Hebburn",label:"Hebburn"},
{value:"Hebden Bridge",label:"Hebden Bridge"},
{value:"Heckington",label:"Heckington"},
{value:"Heckmondwike",label:"Heckmondwike"},
{value:"Hedge End",label:"Hedge End"},
{value:"Hedon",label:"Hedon"},
{value:"Helensburgh",label:"Helensburgh"},
{value:"Helmsley",label:"Helmsley"},
{value:"Helston",label:"Helston"},
{value:"Hemel Hempstead",label:"Hemel Hempstead"},
{value:"Hemsworth",label:"Hemsworth"},
{value:"Henley-in-Arden",label:"Henley-in-Arden"},
{value:"Henley-on-Thames",label:"Henley-on-Thames"},
{value:"Hereford",label:"Hereford"},
{value:"Herne Bay",label:"Herne Bay"},
{value:"Hertford",label:"Hertford"},
{value:"Hessle",label:"Hessle"},
{value:"Heswall",label:"Heswall"},
{value:"Hetton-le-Hole",label:"Hetton-le-Hole"},
{value:"Hexham",label:"Hexham"},
{value:"Heysham",label:"Heysham"},
{value:"Heywood",label:"Heywood"},
{value:"Higham Ferrers",label:"Higham Ferrers"},
{value:"High Bentham",label:"High Bentham"},
{value:"Higher Dunstone",label:"Higher Dunstone"},
{value:"Higher Larrick",label:"Higher Larrick"},
{value:"Highworth",label:"Highworth"},
{value:"High Wycombe",label:"High Wycombe"},
{value:"Hinckley",label:"Hinckley"},
{value:"Hindley",label:"Hindley"},
{value:"Hingham",label:"Hingham"},
{value:"Hitchin",label:"Hitchin"},
{value:"Hoddesdon",label:"Hoddesdon"},
{value:"Holbeach",label:"Holbeach"},
{value:"Holmfirth",label:"Holmfirth"},
{value:"Holsworthy",label:"Holsworthy"},
{value:"Holt",label:"Holt"},
{value:"Holyhead / Caergybi",label:"Holyhead / Caergybi"},
{value:"Holywell / Treffynnon",label:"Holywell / Treffynnon"},
{value:"Holywood",label:"Holywood"},
{value:"Honiton",label:"Honiton"},
{value:"Horbury",label:"Horbury"},
{value:"Horley",label:"Horley"},
{value:"Horncastle",label:"Horncastle"},
{value:"Horndean",label:"Horndean"},
{value:"Hornsea",label:"Hornsea"},
{value:"Horsham",label:"Horsham"},
{value:"Horwich",label:"Horwich"},
{value:"Houghton-le-Spring",label:"Houghton-le-Spring"},
{value:"Houghton Regis",label:"Houghton Regis"},
{value:"Howden",label:"Howden"},
{value:"Hoylake",label:"Hoylake"},
{value:"Hucknall",label:"Hucknall"},
{value:"Huddersfield",label:"Huddersfield"},
{value:"Hugh Town",label:"Hugh Town"},
{value:"Hungerford",label:"Hungerford"},
{value:"Hunstanton",label:"Hunstanton"},
{value:"Huntingdon",label:"Huntingdon"},
{value:"Huntly",label:"Huntly"},
{value:"Hyde",label:"Hyde"},
{value:"Hythe",label:"Hythe"},
{value:"Ibstock",label:"Ibstock"},
{value:"Ilfracombe",label:"Ilfracombe"},
{value:"Ilkeston",label:"Ilkeston"},
{value:"Ilkley",label:"Ilkley"},
{value:"Ilminster",label:"Ilminster"},
{value:"Immingham",label:"Immingham"},
{value:"Ince-in-Makerfield",label:"Ince-in-Makerfield"},
{value:"Innerleithen",label:"Innerleithen"},
{value:"Inveraray",label:"Inveraray"},
{value:"Inverbervie",label:"Inverbervie"},
{value:"Invergordon",label:"Invergordon"},
{value:"Inverkeithing",label:"Inverkeithing"},
{value:"Inverness / Inbhir Nis",label:"Inverness / Inbhir Nis"},
{value:"Inverurie",label:"Inverurie"},
{value:"Ipswich",label:"Ipswich"},
{value:"Irlam",label:"Irlam"},
{value:"Irthlingborough",label:"Irthlingborough"},
{value:"Irvine",label:"Irvine"},
{value:"Ivybridge",label:"Ivybridge"},
{value:"Jarrow",label:"Jarrow"},
{value:"Jedburgh",label:"Jedburgh"},
{value:"Johnstone",label:"Johnstone"},
{value:"Kearsley",label:"Kearsley"},
{value:"Keighley",label:"Keighley"},
{value:"Keith",label:"Keith"},
{value:"Kelso",label:"Kelso"},
{value:"Kempston",label:"Kempston"},
{value:"Kendal",label:"Kendal"},
{value:"Kenilworth",label:"Kenilworth"},
{value:"Kesgrave",label:"Kesgrave"},
{value:"Keswick",label:"Keswick"},
{value:"Kettering",label:"Kettering"},
{value:"Keynsham",label:"Keynsham"},
{value:"Kidderminster",label:"Kidderminster"},
{value:"Kidlington",label:"Kidlington"},
{value:"Kidsgrove",label:"Kidsgrove"},
{value:"Kidwelly / Cydweli",label:"Kidwelly / Cydweli"},
{value:"Kilkeel",label:"Kilkeel"},
{value:"Kilmarnock",label:"Kilmarnock"},
{value:"Kilsyth",label:"Kilsyth"},
{value:"Kilwinning",label:"Kilwinning"},
{value:"Kimberley",label:"Kimberley"},
{value:"Kinghorn",label:"Kinghorn"},
{value:"Kingsbridge",label:"Kingsbridge"},
{value:"King's Lynn",label:"King's Lynn"},
{value:"Kingsteignton",label:"Kingsteignton"},
{value:"Kingston upon Hull",label:"Kingston upon Hull"},
{value:"Kingswinford",label:"Kingswinford"},
{value:"Kington",label:"Kington"},
{value:"Kingussie",label:"Kingussie"},
{value:"Kinross",label:"Kinross"},
{value:"Kintore",label:"Kintore"},
{value:"Kirkby",label:"Kirkby"},
{value:"Kirkby-in-Ashfield",label:"Kirkby-in-Ashfield"},
{value:"Kirkby Lonsdale",label:"Kirkby Lonsdale"},
{value:"Kirkbymoorside",label:"Kirkbymoorside"},
{value:"Kirkby Stephen",label:"Kirkby Stephen"},
{value:"Kirkcaldy",label:"Kirkcaldy"},
{value:"Kirkcudbright",label:"Kirkcudbright"},
{value:"Kirkham",label:"Kirkham"},
{value:"Kirkintilloch",label:"Kirkintilloch"},
{value:"Kirkwall",label:"Kirkwall"},
{value:"Kirriemuir",label:"Kirriemuir"},
{value:"Kirton in Lindsey",label:"Kirton in Lindsey"},
{value:"Knaresborough",label:"Knaresborough"},
{value:"Knighton / Tref-y-Clawdd",label:"Knighton / Tref-y-Clawdd"},
{value:"Knottingley",label:"Knottingley"},
{value:"Knutsford",label:"Knutsford"},
{value:"Ladybank",label:"Ladybank"},
{value:"Lampeter / Llanbedr Pont Steffan",label:"Lampeter / Llanbedr Pont Steffan"},
{value:"Lanark",label:"Lanark"},
{value:"Lancaster",label:"Lancaster"},
{value:"Langholm",label:"Langholm"},
{value:"Langport",label:"Langport"},
{value:"Largs",label:"Largs"},
{value:"Larkhall",label:"Larkhall"},
{value:"Larne",label:"Larne"},
{value:"Lauder",label:"Lauder"},
{value:"Laugharne / Talacharn",label:"Laugharne / Talacharn"},
{value:"Launceston",label:"Launceston"},
{value:"Laurencekirk",label:"Laurencekirk"},
{value:"Leatherhead",label:"Leatherhead"},
{value:"Lechlade-on-Thames",label:"Lechlade-on-Thames"},
{value:"Ledbury",label:"Ledbury"},
{value:"Leeds",label:"Leeds"},
{value:"Leek",label:"Leek"},
{value:"Lees",label:"Lees"},
{value:"Leicester",label:"Leicester"},
{value:"Leigh",label:"Leigh"},
{value:"Leigh-on-Sea",label:"Leigh-on-Sea"},
{value:"Leighton Buzzard",label:"Leighton Buzzard"},
{value:"Leiston",label:"Leiston"},
{value:"Leominster",label:"Leominster"},
{value:"Lerwick",label:"Lerwick"},
{value:"Leslie",label:"Leslie"},
{value:"Letchworth",label:"Letchworth"},
{value:"Leven",label:"Leven"},
{value:"Lewes",label:"Lewes"},
{value:"Leyburn",label:"Leyburn"},
{value:"Leyland",label:"Leyland"},
{value:"Lichfield",label:"Lichfield"},
{value:"Limavady",label:"Limavady"},
{value:"Lincoln",label:"Lincoln"},
{value:"Linlithgow",label:"Linlithgow"},
{value:"Lisburn",label:"Lisburn"},
{value:"Liskeard",label:"Liskeard"},
{value:"Litherland",label:"Litherland"},
{value:"Littleborough",label:"Littleborough"},
{value:"Littlehampton",label:"Littlehampton"},
{value:"Little Lever",label:"Little Lever"},
{value:"Liverpool",label:"Liverpool"},
{value:"Liversedge",label:"Liversedge"},
{value:"Livingston",label:"Livingston"},
{value:"Llandeilo",label:"Llandeilo"},
{value:"Llandovery / Llanymddyfri",label:"Llandovery / Llanymddyfri"},
{value:"Llandrindod Wells / Llandrindod",label:"Llandrindod Wells / Llandrindod"},
{value:"Llandudno",label:"Llandudno"},
{value:"Llandysul",label:"Llandysul"},
{value:"Llanelli",label:"Llanelli"},
{value:"Llanfair Caereinion",label:"Llanfair Caereinion"},
{value:"Llanfairfechan",label:"Llanfairfechan"},
{value:"Llanfyllin",label:"Llanfyllin"},
{value:"Llangefni",label:"Llangefni"},
{value:"Llangollen",label:"Llangollen"},
{value:"Llanidloes",label:"Llanidloes"},
{value:"Llanrwst",label:"Llanrwst"},
{value:"Llantrisant",label:"Llantrisant"},
{value:"Llantwit Major / Llanilltud Fawr",label:"Llantwit Major / Llanilltud Fawr"},
{value:"Llanwrtyd Wells",label:"Llanwrtyd Wells"},
{value:"Llanybydder / Llanybyther",label:"Llanybydder / Llanybyther"},
{value:"Loanhead",label:"Loanhead"},
{value:"Lochgelly",label:"Lochgelly"},
{value:"Lochgilphead / Ceann Loch Gilb",label:"Lochgilphead / Ceann Loch Gilb"},
{value:"Lochmaben",label:"Lochmaben"},
{value:"Lockerbie",label:"Lockerbie"},
{value:"Loddon",label:"Loddon"},
{value:"Loftus",label:"Loftus"},
{value:"London",label:"London"},
{value:"Longbenton",label:"Longbenton"},
{value:"Long Eaton",label:"Long Eaton"},
{value:"Longridge",label:"Longridge"},
{value:"Long Sutton",label:"Long Sutton"},
{value:"Longtown",label:"Longtown"},
{value:"Looe",label:"Looe"},
{value:"Lossiemouth",label:"Lossiemouth"},
{value:"Lostwithiel",label:"Lostwithiel"},
{value:"Loughborough",label:"Loughborough"},
{value:"Loughor / Casllwchwr",label:"Loughor / Casllwchwr"},
{value:"Loughton",label:"Loughton"},
{value:"Louth",label:"Louth"},
{value:"Lowestoft",label:"Lowestoft"},
{value:"Ludgershall",label:"Ludgershall"},
{value:"Ludlow",label:"Ludlow"},
{value:"Lurgan",label:"Lurgan"},
{value:"Luton",label:"Luton"},
{value:"Lutterworth",label:"Lutterworth"},
{value:"Lydd",label:"Lydd"},
{value:"Lydney",label:"Lydney"},
{value:"Lyme Regis",label:"Lyme Regis"},
{value:"Lymington",label:"Lymington"},
{value:"Lymm",label:"Lymm"},
{value:"Lynton",label:"Lynton"},
{value:"Lytham St Anne's",label:"Lytham St Anne's"},
{value:"Mablethorpe",label:"Mablethorpe"},
{value:"Macclesfield",label:"Macclesfield"},
{value:"Macduff",label:"Macduff"},
{value:"Machynlleth",label:"Machynlleth"},
{value:"Madeley",label:"Madeley"},
{value:"Maesteg",label:"Maesteg"},
{value:"Magherafelt",label:"Magherafelt"},
{value:"Maghull",label:"Maghull"},
{value:"Maidenhead",label:"Maidenhead"},
{value:"Maidstone",label:"Maidstone"},
{value:"Maldon",label:"Maldon"},
{value:"Malmesbury",label:"Malmesbury"},
{value:"Maltby",label:"Maltby"},
{value:"Malton",label:"Malton"},
{value:"Manchester",label:"Manchester"},
{value:"Manningtree",label:"Manningtree"},
{value:"Mansfield",label:"Mansfield"},
{value:"Mansfield Woodhouse",label:"Mansfield Woodhouse"},
{value:"March",label:"March"},
{value:"Margate",label:"Margate"},
{value:"Market Bosworth",label:"Market Bosworth"},
{value:"Market Deeping",label:"Market Deeping"},
{value:"Market Drayton",label:"Market Drayton"},
{value:"Market Harborough",label:"Market Harborough"},
{value:"Market Jew / Marazion",label:"Market Jew / Marazion"},
{value:"Market Rasen",label:"Market Rasen"},
{value:"Market Warsop",label:"Market Warsop"},
{value:"Market Weighton",label:"Market Weighton"},
{value:"Markinch",label:"Markinch"},
{value:"Marlborough",label:"Marlborough"},
{value:"Marlow",label:"Marlow"},
{value:"Marple",label:"Marple"},
{value:"Marske-by-the-Sea",label:"Marske-by-the-Sea"},
{value:"Maryport",label:"Maryport"},
{value:"Masham",label:"Masham"},
{value:"Matlock",label:"Matlock"},
{value:"Maybole",label:"Maybole"},
{value:"Meadow Well",label:"Meadow Well"},
{value:"Melksham",label:"Melksham"},
{value:"Melrose",label:"Melrose"},
{value:"Meltham",label:"Meltham"},
{value:"Melton Mowbray",label:"Melton Mowbray"},
{value:"Menai Bridge / Porthaethwy",label:"Menai Bridge / Porthaethwy"},
{value:"Mere",label:"Mere"},
{value:"Merthyr Tydfil / Merthyr Tudful",label:"Merthyr Tydfil / Merthyr Tudful"},
{value:"Methil",label:"Methil"},
{value:"Mexborough",label:"Mexborough"},
{value:"Middleham",label:"Middleham"},
{value:"Middlesbrough",label:"Middlesbrough"},
{value:"Middleton",label:"Middleton"},
{value:"Middlewich",label:"Middlewich"},
{value:"Midhurst",label:"Midhurst"},
{value:"Midsomer Norton",label:"Midsomer Norton"},
{value:"Mildenhall",label:"Mildenhall"},
{value:"Milford Haven / Aberdaugleddau",label:"Milford Haven / Aberdaugleddau"},
{value:"Millom",label:"Millom"},
{value:"Millport",label:"Millport"},
{value:"Milngavie",label:"Milngavie"},
{value:"Milnrow",label:"Milnrow"},
{value:"Milton Keynes",label:"Milton Keynes"},
{value:"Minchinhampton",label:"Minchinhampton"},
{value:"Minehead",label:"Minehead"},
{value:"Minster",label:"Minster"},
{value:"Mirfield",label:"Mirfield"},
{value:"Mitcheldean",label:"Mitcheldean"},
{value:"Moffat",label:"Moffat"},
{value:"Mold / Yr Wyddgrug",label:"Mold / Yr Wyddgrug"},
{value:"Monifieth",label:"Monifieth"},
{value:"Monmouth / Trefynwy",label:"Monmouth / Trefynwy"},
{value:"Montgomery / Trefaldwyn",label:"Montgomery / Trefaldwyn"},
{value:"Montrose",label:"Montrose"},
{value:"Morecambe",label:"Morecambe"},
{value:"Moretonhampstead",label:"Moretonhampstead"},
{value:"Moreton-in-Marsh",label:"Moreton-in-Marsh"},
{value:"Morley",label:"Morley"},
{value:"Morpeth",label:"Morpeth"},
{value:"Mossley",label:"Mossley"},
{value:"Motherwell",label:"Motherwell"},
{value:"Mountain Ash / Aberpennar",label:"Mountain Ash / Aberpennar"},
{value:"Much Wenlock",label:"Much Wenlock"},
{value:"Musselburgh",label:"Musselburgh"},
{value:"Nailsea",label:"Nailsea"},
{value:"Nailsworth",label:"Nailsworth"},
{value:"Nairn",label:"Nairn"},
{value:"Nantwich",label:"Nantwich"},
{value:"Nantyglo",label:"Nantyglo"},
{value:"Narberth / Arberth",label:"Narberth / Arberth"},
{value:"Neath / Castell-nedd",label:"Neath / Castell-nedd"},
{value:"Needham Market",label:"Needham Market"},
{value:"Nefyn",label:"Nefyn"},
{value:"Nelson",label:"Nelson"},
{value:"Neston",label:"Neston"},
{value:"New Alresford",label:"New Alresford"},
{value:"Newark-on-Trent",label:"Newark-on-Trent"},
{value:"Newbiggin-by-the-Sea",label:"Newbiggin-by-the-Sea"},
{value:"Newbridge / Trecceln",label:"Newbridge / Trecceln"},
{value:"Newburgh",label:"Newburgh"},
{value:"Newbury",label:"Newbury"},
{value:"Newcastle",label:"Newcastle"},
{value:"Newcastle Emlyn / Castell Newydd Emlyn",label:"Newcastle Emlyn / Castell Newydd Emlyn"},
{value:"Newcastle-under-Lyme",label:"Newcastle-under-Lyme"},
{value:"Newcastle upon Tyne",label:"Newcastle upon Tyne"},
{value:"Newent",label:"Newent"},
{value:"New Galloway",label:"New Galloway"},
{value:"Newhaven",label:"Newhaven"},
{value:"Newlyn",label:"Newlyn"},
{value:"Newmarket",label:"Newmarket"},
{value:"New Mills",label:"New Mills"},
{value:"Newmilns",label:"Newmilns"},
{value:"New Milton",label:"New Milton"},
{value:"Newport",label:"Newport"},
{value:"Newport",label:"Newport"},
{value:"Newport / Casnewydd",label:"Newport / Casnewydd"},
{value:"Newport-on-Tay",label:"Newport-on-Tay"},
{value:"Newport Pagnell",label:"Newport Pagnell"},
{value:"Newport / Trefdraeth",label:"Newport / Trefdraeth"},
{value:"Newquay",label:"Newquay"},
{value:"New Quay / Ceinewydd",label:"New Quay / Ceinewydd"},
{value:"New Romney",label:"New Romney"},
{value:"Newry",label:"Newry"},
{value:"Newton Abbot",label:"Newton Abbot"},
{value:"Newton Aycliffe",label:"Newton Aycliffe"},
{value:"Newton-le-Willows",label:"Newton-le-Willows"},
{value:"Newton Stewart",label:"Newton Stewart"},
{value:"Newtownabbey",label:"Newtownabbey"},
{value:"Newtownards",label:"Newtownards"},
{value:"Newtown / Y Drenewydd",label:"Newtown / Y Drenewydd"},
{value:"Neyland",label:"Neyland"},
{value:"Normanton",label:"Normanton"},
{value:"Northallerton",label:"Northallerton"},
{value:"Northam",label:"Northam"},
{value:"Northampton",label:"Northampton"},
{value:"North Berwick",label:"North Berwick"},
{value:"Northfleet",label:"Northfleet"},
{value:"North Hykeham",label:"North Hykeham"},
{value:"Northleach",label:"Northleach"},
{value:"North Petherton",label:"North Petherton"},
{value:"North Tawton",label:"North Tawton"},
{value:"North Walsham",label:"North Walsham"},
{value:"Northwich",label:"Northwich"},
{value:"Norton-on-Derwent",label:"Norton-on-Derwent"},
{value:"Norwich",label:"Norwich"},
{value:"Nottingham",label:"Nottingham"},
{value:"Nuneaton",label:"Nuneaton"},
{value:"Oakham",label:"Oakham"},
{value:"Oban",label:"Oban"},
{value:"Okehampton",label:"Okehampton"},
{value:"Oldbury",label:"Oldbury"},
{value:"Oldham",label:"Oldham"},
{value:"Oldmeldrum",label:"Oldmeldrum"},
{value:"Olney",label:"Olney"},
{value:"Omagh",label:"Omagh"},
{value:"Ormskirk",label:"Ormskirk"},
{value:"Ossett",label:"Ossett"},
{value:"Oswaldtwistle",label:"Oswaldtwistle"},
{value:"Oswestry / Croesoswallt",label:"Oswestry / Croesoswallt"},
{value:"Otley",label:"Otley"},
{value:"Ottery St Mary",label:"Ottery St Mary"},
{value:"Oundle",label:"Oundle"},
{value:"Oxford",label:"Oxford"},
{value:"Oxted",label:"Oxted"},
{value:"Paddock Wood",label:"Paddock Wood"},
{value:"Padiham",label:"Padiham"},
{value:"Padstow",label:"Padstow"},
{value:"Paignton",label:"Paignton"},
{value:"Painswick",label:"Painswick"},
{value:"Paisley",label:"Paisley"},
{value:"Partington",label:"Partington"},
{value:"Pateley Bridge",label:"Pateley Bridge"},
{value:"Peacehaven",label:"Peacehaven"},
{value:"Peebles",label:"Peebles"},
{value:"Peel",label:"Peel"},
{value:"Pembroke Dock / Doc Penfro",label:"Pembroke Dock / Doc Penfro"},
{value:"Pembroke / Penfro",label:"Pembroke / Penfro"},
{value:"Penarth",label:"Penarth"},
{value:"Pencoed",label:"Pencoed"},
{value:"Penicuik",label:"Penicuik"},
{value:"Penistone",label:"Penistone"},
{value:"Penkridge",label:"Penkridge"},
{value:"Penmaenmawr",label:"Penmaenmawr"},
{value:"Penrith",label:"Penrith"},
{value:"Penryn",label:"Penryn"},
{value:"Penzance",label:"Penzance"},
{value:"Pershore",label:"Pershore"},
{value:"Perth",label:"Perth"},
{value:"Peterborough",label:"Peterborough"},
{value:"Peterhead",label:"Peterhead"},
{value:"Peterlee",label:"Peterlee"},
{value:"Petersfield",label:"Petersfield"},
{value:"Petworth",label:"Petworth"},
{value:"Pickering",label:"Pickering"},
{value:"Pitlochry",label:"Pitlochry"},
{value:"Pittenweem",label:"Pittenweem"},
{value:"Plymouth",label:"Plymouth"},
{value:"Pocklington",label:"Pocklington"},
{value:"Polegate",label:"Polegate"},
{value:"Pontardawe",label:"Pontardawe"},
{value:"Pontarddulais",label:"Pontarddulais"},
{value:"Pontefract",label:"Pontefract"},
{value:"Ponteland",label:"Ponteland"},
{value:"Pontllanfraith",label:"Pontllanfraith"},
{value:"Pontycymer",label:"Pontycymer"},
{value:"Pontypool / Pont-y-pŵl",label:"Pontypool / Pont-y-pŵl"},
{value:"Pontypridd",label:"Pontypridd"},
{value:"Poole",label:"Poole"},
{value:"Portadown",label:"Portadown"},
{value:"Port Glasgow",label:"Port Glasgow"},
{value:"Porth",label:"Porth"},
{value:"Porthcawl",label:"Porthcawl"},
{value:"Porthmadog",label:"Porthmadog"},
{value:"Portishead",label:"Portishead"},
{value:"Portlethen",label:"Portlethen"},
{value:"Portrush",label:"Portrush"},
{value:"Portsmouth",label:"Portsmouth"},
{value:"Portsoy",label:"Portsoy"},
{value:"Portstewart",label:"Portstewart"},
{value:"Port Talbot",label:"Port Talbot"},
{value:"Potters Bar",label:"Potters Bar"},
{value:"Potton",label:"Potton"},
{value:"Poulton-le-Fylde",label:"Poulton-le-Fylde"},
{value:"Poynton",label:"Poynton"},
{value:"Prescot",label:"Prescot"},
{value:"Prestatyn",label:"Prestatyn"},
{value:"Presteigne / Llanandras",label:"Presteigne / Llanandras"},
{value:"Preston",label:"Preston"},
{value:"Prestonpans",label:"Prestonpans"},
{value:"Prestwick",label:"Prestwick"},
{value:"Princes Risborough",label:"Princes Risborough"},
{value:"Prudhoe",label:"Prudhoe"},
{value:"Pudsey",label:"Pudsey"},
{value:"Pwllheli",label:"Pwllheli"},
{value:"Queenborough",label:"Queenborough"},
{value:"Queensferry",label:"Queensferry"},
{value:"Radcliffe",label:"Radcliffe"},
{value:"Radlett",label:"Radlett"},
{value:"Radstock",label:"Radstock"},
{value:"Rainford",label:"Rainford"},
{value:"Ramsbottom",label:"Ramsbottom"},
{value:"Ramsey",label:"Ramsey"},
{value:"Ramsey",label:"Ramsey"},
{value:"Ramsgate",label:"Ramsgate"},
{value:"Randalstown",label:"Randalstown"},
{value:"Raunds",label:"Raunds"},
{value:"Rawmarsh",label:"Rawmarsh"},
{value:"Rawtenstall",label:"Rawtenstall"},
{value:"Rayleigh",label:"Rayleigh"},
{value:"Reading",label:"Reading"},
{value:"Redcar",label:"Redcar"},
{value:"Redditch",label:"Redditch"},
{value:"Redhill",label:"Redhill"},
{value:"Redruth",label:"Redruth"},
{value:"Reepham",label:"Reepham"},
{value:"Reigate",label:"Reigate"},
{value:"Renfrew",label:"Renfrew"},
{value:"Retford",label:"Retford"},
{value:"Rhayader / Rhaeadr Gwy",label:"Rhayader / Rhaeadr Gwy"},
{value:"Rhondda",label:"Rhondda"},
{value:"Rhosgadfan",label:"Rhosgadfan"},
{value:"Rhuddlan",label:"Rhuddlan"},
{value:"Rhyl",label:"Rhyl"},
{value:"Rhymney / Rhymni",label:"Rhymney / Rhymni"},
{value:"Richmond",label:"Richmond"},
{value:"Richmond",label:"Richmond"},
{value:"Rickmansworth",label:"Rickmansworth"},
{value:"Ringwood",label:"Ringwood"},
{value:"Ripley",label:"Ripley"},
{value:"Ripon",label:"Ripon"},
{value:"Risca / Rhisga",label:"Risca / Rhisga"},
{value:"Rishton",label:"Rishton"},
{value:"Rochdale",label:"Rochdale"},
{value:"Rochester",label:"Rochester"},
{value:"Rochford",label:"Rochford"},
{value:"Romiley",label:"Romiley"},
{value:"Romsey",label:"Romsey"},
{value:"Rosehearty",label:"Rosehearty"},
{value:"Ross-on-Wye",label:"Ross-on-Wye"},
{value:"Rothbury",label:"Rothbury"},
{value:"Rotherham",label:"Rotherham"},
{value:"Rothes",label:"Rothes"},
{value:"Rothesay",label:"Rothesay"},
{value:"Rothwell",label:"Rothwell"},
{value:"Rowley Regis",label:"Rowley Regis"},
{value:"Royal Leamington Spa",label:"Royal Leamington Spa"},
{value:"Royal Sutton Coldfield",label:"Royal Sutton Coldfield"},
{value:"Royal Tunbridge Wells",label:"Royal Tunbridge Wells"},
{value:"Royal Wootton Bassett",label:"Royal Wootton Bassett"},
{value:"Royston",label:"Royston"},
{value:"Royston",label:"Royston"},
{value:"Royton",label:"Royton"},
{value:"Rugby",label:"Rugby"},
{value:"Rugeley",label:"Rugeley"},
{value:"Runcorn",label:"Runcorn"},
{value:"Rushden",label:"Rushden"},
{value:"Rutherglen",label:"Rutherglen"},
{value:"Ruthin / Rhuthun",label:"Ruthin / Rhuthun"},
{value:"Ryde",label:"Ryde"},
{value:"Rye",label:"Rye"},
{value:"Ryton",label:"Ryton"},
{value:"Saffron Walden",label:"Saffron Walden"},
{value:"Salcombe",label:"Salcombe"},
{value:"Sale",label:"Sale"},
{value:"Salford",label:"Salford"},
{value:"Salisbury",label:"Salisbury"},
{value:"Saltash",label:"Saltash"},
{value:"Saltburn-by-the-Sea",label:"Saltburn-by-the-Sea"},
{value:"Saltcoats",label:"Saltcoats"},
{value:"Sandbach",label:"Sandbach"},
{value:"Sandhurst",label:"Sandhurst"},
{value:"Sandiacre",label:"Sandiacre"},
{value:"Sandown",label:"Sandown"},
{value:"Sandwich",label:"Sandwich"},
{value:"Sandy",label:"Sandy"},
{value:"Sanquhar",label:"Sanquhar"},
{value:"Sawbridgeworth",label:"Sawbridgeworth"},
{value:"Saxmundham",label:"Saxmundham"},
{value:"Scarborough",label:"Scarborough"},
{value:"Scunthorpe",label:"Scunthorpe"},
{value:"Seaford",label:"Seaford"},
{value:"Seaham",label:"Seaham"},
{value:"Seaton",label:"Seaton"},
{value:"Sedbergh",label:"Sedbergh"},
{value:"Sedgefield",label:"Sedgefield"},
{value:"Sedgley",label:"Sedgley"},
{value:"Selby",label:"Selby"},
{value:"Selkirk",label:"Selkirk"},
{value:"Selsey",label:"Selsey"},
{value:"Settle",label:"Settle"},
{value:"Sevenoaks",label:"Sevenoaks"},
{value:"Shaftesbury",label:"Shaftesbury"},
{value:"Shanklin",label:"Shanklin"},
{value:"Shaw",label:"Shaw"},
{value:"Sheerness",label:"Sheerness"},
{value:"Sheffield",label:"Sheffield"},
{value:"Shefford",label:"Shefford"},
{value:"Shepshed",label:"Shepshed"},
{value:"Shepton Mallet",label:"Shepton Mallet"},
{value:"Sherborne",label:"Sherborne"},
{value:"Sherford",label:"Sherford"},
{value:"Sheringham",label:"Sheringham"},
{value:"Shildon",label:"Shildon"},
{value:"Shipley",label:"Shipley"},
{value:"Shipston-on-Stour",label:"Shipston-on-Stour"},
{value:"Shirebrook",label:"Shirebrook"},
{value:"Shoreham-by-Sea",label:"Shoreham-by-Sea"},
{value:"Shotton",label:"Shotton"},
{value:"Shrewsbury",label:"Shrewsbury"},
{value:"Sidmouth",label:"Sidmouth"},
{value:"Silloth",label:"Silloth"},
{value:"Silsden",label:"Silsden"},
{value:"Sittingbourne",label:"Sittingbourne"},
{value:"Skegness",label:"Skegness"},
{value:"Skelmersdale",label:"Skelmersdale"},
{value:"Skelton",label:"Skelton"},
{value:"Skipton",label:"Skipton"},
{value:"Sleaford",label:"Sleaford"},
{value:"Slough",label:"Slough"},
{value:"Smethwick",label:"Smethwick"},
{value:"Snodland",label:"Snodland"},
{value:"Soham",label:"Soham"},
{value:"Solihull",label:"Solihull"},
{value:"Somerton",label:"Somerton"},
{value:"Southam",label:"Southam"},
{value:"Southampton",label:"Southampton"},
{value:"Southborough",label:"Southborough"},
{value:"South Cave",label:"South Cave"},
{value:"South Elmsall",label:"South Elmsall"},
{value:"Southend-on-Sea",label:"Southend-on-Sea"},
{value:"South Kirkby",label:"South Kirkby"},
{value:"Southminster",label:"Southminster"},
{value:"South Molton",label:"South Molton"},
{value:"South Petherton",label:"South Petherton"},
{value:"Southport",label:"Southport"},
{value:"South Shields",label:"South Shields"},
{value:"Southwell",label:"Southwell"},
{value:"Southwick",label:"Southwick"},
{value:"Southwold",label:"Southwold"},
{value:"South Woodham Ferrers",label:"South Woodham Ferrers"},
{value:"Sowerby Bridge",label:"Sowerby Bridge"},
{value:"Spalding",label:"Spalding"},
{value:"Spennymoor",label:"Spennymoor"},
{value:"Spilsby",label:"Spilsby"},
{value:"Stafford",label:"Stafford"},
{value:"Staines-upon-Thames",label:"Staines-upon-Thames"},
{value:"St Albans",label:"St Albans"},
{value:"Stalbridge",label:"Stalbridge"},
{value:"Stalham",label:"Stalham"},
{value:"Stalybridge",label:"Stalybridge"},
{value:"Stamford",label:"Stamford"},
{value:"Standish",label:"Standish"},
{value:"St Andrews",label:"St Andrews"},
{value:"Stanford-le-Hope",label:"Stanford-le-Hope"},
{value:"Stanhope",label:"Stanhope"},
{value:"Stanley",label:"Stanley"},
{value:"Stansted Mountfitchet",label:"Stansted Mountfitchet"},
{value:"Stapleford",label:"Stapleford"},
{value:"St Asaph / Llanelwy",label:"St Asaph / Llanelwy"},
{value:"St Austell",label:"St Austell"},
{value:"Staveley",label:"Staveley"},
{value:"St Blazey",label:"St Blazey"},
{value:"St Clears / Sanclêr",label:"St Clears / Sanclêr"},
{value:"St Columb Major",label:"St Columb Major"},
{value:"St Davids / Tyddewi",label:"St Davids / Tyddewi"},
{value:"Stevenage",label:"Stevenage"},
{value:"Stevenston",label:"Stevenston"},
{value:"Stewarton",label:"Stewarton"},
{value:"Steyning",label:"Steyning"},
{value:"St Helens",label:"St Helens"},
{value:"Stirling",label:"Stirling"},
{value:"St Ives",label:"St Ives"},
{value:"St Ives",label:"St Ives"},
{value:"St Just / St Just in Penwith",label:"St Just / St Just in Penwith"},
{value:"St Neots",label:"St Neots"},
{value:"Stockport",label:"Stockport"},
{value:"Stocksbridge",label:"Stocksbridge"},
{value:"Stockton-on-Tees",label:"Stockton-on-Tees"},
{value:"Stoke-on-Trent",label:"Stoke-on-Trent"},
{value:"Stone",label:"Stone"},
{value:"Stonehaven",label:"Stonehaven"},
{value:"Stonehouse",label:"Stonehouse"},
{value:"Stornoway / Steòrnabhagh",label:"Stornoway / Steòrnabhagh"},
{value:"Stotfold",label:"Stotfold"},
{value:"Stourbridge",label:"Stourbridge"},
{value:"Stourport-on-Severn",label:"Stourport-on-Severn"},
{value:"Stowmarket",label:"Stowmarket"},
{value:"Stow-on-the-Wold",label:"Stow-on-the-Wold"},
{value:"Strabane",label:"Strabane"},
{value:"Stranraer",label:"Stranraer"},
{value:"Stratford-upon-Avon",label:"Stratford-upon-Avon"},
{value:"Stratton",label:"Stratton"},
{value:"Street",label:"Street"},
{value:"Stretford",label:"Stretford"},
{value:"Stromness",label:"Stromness"},
{value:"Stroud",label:"Stroud"},
{value:"Sturminster Newton",label:"Sturminster Newton"},
{value:"Sudbury",label:"Sudbury"},
{value:"Sunbury",label:"Sunbury"},
{value:"Sunbury-on-Thames",label:"Sunbury-on-Thames"},
{value:"Sunderland",label:"Sunderland"},
{value:"Sutton Coldfield",label:"Sutton Coldfield"},
{value:"Sutton in Ashfield",label:"Sutton in Ashfield"},
{value:"Swadlincote",label:"Swadlincote"},
{value:"Swaffham",label:"Swaffham"},
{value:"Swanage",label:"Swanage"},
{value:"Swanley",label:"Swanley"},
{value:"Swanscombe",label:"Swanscombe"},
{value:"Swansea / Abertawe",label:"Swansea / Abertawe"},
{value:"Swindon",label:"Swindon"},
{value:"Swinton",label:"Swinton"},
{value:"Syston",label:"Syston"},
{value:"Tadcaster",label:"Tadcaster"},
{value:"Tadley",label:"Tadley"},
{value:"Tain",label:"Tain"},
{value:"Talbot Green",label:"Talbot Green"},
{value:"Talgarth",label:"Talgarth"},
{value:"Tamworth",label:"Tamworth"},
{value:"Taunton",label:"Taunton"},
{value:"Tavistock",label:"Tavistock"},
{value:"Tayport",label:"Tayport"},
{value:"Teignmouth",label:"Teignmouth"},
{value:"Telford",label:"Telford"},
{value:"Tenbury Wells",label:"Tenbury Wells"},
{value:"Tenby / Dinbych-y-Pysgod",label:"Tenby / Dinbych-y-Pysgod"},
{value:"Tenterden",label:"Tenterden"},
{value:"Tetbury",label:"Tetbury"},
{value:"Tewkesbury",label:"Tewkesbury"},
{value:"Thame",label:"Thame"},
{value:"Thatcham",label:"Thatcham"},
{value:"Thaxted",label:"Thaxted"},
{value:"Thetford",label:"Thetford"},
{value:"Thirsk",label:"Thirsk"},
{value:"Thornaby-on-Tees",label:"Thornaby-on-Tees"},
{value:"Thornbury",label:"Thornbury"},
{value:"Thorne",label:"Thorne"},
{value:"Thornton",label:"Thornton"},
{value:"Thrapston",label:"Thrapston"},
{value:"Thurnscoe",label:"Thurnscoe"},
{value:"Thurso",label:"Thurso"},
{value:"Tickhill",label:"Tickhill"},
{value:"Tidworth",label:"Tidworth"},
{value:"Tilbury",label:"Tilbury"},
{value:"Tillicoultry",label:"Tillicoultry"},
{value:"Tipton",label:"Tipton"},
{value:"Tiverton",label:"Tiverton"},
{value:"Tobermory",label:"Tobermory"},
{value:"Todmorden",label:"Todmorden"},
{value:"Tonbridge",label:"Tonbridge"},
{value:"Tonypandy",label:"Tonypandy"},
{value:"Topsham",label:"Topsham"},
{value:"Torpoint",label:"Torpoint"},
{value:"Torquay",label:"Torquay"},
{value:"Totnes",label:"Totnes"},
{value:"Totton",label:"Totton"},
{value:"Towcester",label:"Towcester"},
{value:"Tow Law",label:"Tow Law"},
{value:"Tranent",label:"Tranent"},
{value:"Trawden",label:"Trawden"},
{value:"Tredegar",label:"Tredegar"},
{value:"Tregaron",label:"Tregaron"},
{value:"Treharris",label:"Treharris"},
{value:"Treherbert",label:"Treherbert"},
{value:"Treorchy / Treorci",label:"Treorchy / Treorci"},
{value:"Tring",label:"Tring"},
{value:"Troon",label:"Troon"},
{value:"Trowbridge",label:"Trowbridge"},
{value:"Truro",label:"Truro"},
{value:"Turriff",label:"Turriff"},
{value:"Tyldesley",label:"Tyldesley"},
{value:"Tynemouth",label:"Tynemouth"},
{value:"Tywyn",label:"Tywyn"},
{value:"Uckfield",label:"Uckfield"},
{value:"Uddingston",label:"Uddingston"},
{value:"Ulverston",label:"Ulverston"},
{value:"Uppingham",label:"Uppingham"},
{value:"Urmston",label:"Urmston"},
{value:"Usk / Brynbuga",label:"Usk / Brynbuga"},
{value:"Uttoxeter",label:"Uttoxeter"},
{value:"Ventnor",label:"Ventnor"},
{value:"Verwood",label:"Verwood"},
{value:"Wadebridge",label:"Wadebridge"},
{value:"Wadhurst",label:"Wadhurst"},
{value:"Wainfleet All Saints",label:"Wainfleet All Saints"},
{value:"Wakefield",label:"Wakefield"},
{value:"Walkden",label:"Walkden"},
{value:"Wallasey",label:"Wallasey"},
{value:"Wallingford",label:"Wallingford"},
{value:"Wallsend",label:"Wallsend"},
{value:"Walsall",label:"Walsall"},
{value:"Waltham Abbey",label:"Waltham Abbey"},
{value:"Waltham Cross",label:"Waltham Cross"},
{value:"Walton-on-Thames",label:"Walton-on-Thames"},
{value:"Walton-on-the-Naze",label:"Walton-on-the-Naze"},
{value:"Wantage",label:"Wantage"},
{value:"Ware",label:"Ware"},
{value:"Wareham",label:"Wareham"},
{value:"Warlingham",label:"Warlingham"},
{value:"Warminster",label:"Warminster"},
{value:"Warrenpoint",label:"Warrenpoint"},
{value:"Warrington",label:"Warrington"},
{value:"Warwick",label:"Warwick"},
{value:"Washington",label:"Washington"},
{value:"Watchet",label:"Watchet"},
{value:"Watford",label:"Watford"},
{value:"Wath upon Dearne",label:"Wath upon Dearne"},
{value:"Watlington",label:"Watlington"},
{value:"Watton",label:"Watton"},
{value:"Wednesbury",label:"Wednesbury"},
{value:"Wellingborough",label:"Wellingborough"},
{value:"Wellington",label:"Wellington"},
{value:"Wells",label:"Wells"},
{value:"Wells-next-the-Sea",label:"Wells-next-the-Sea"},
{value:"Welshpool / Y Trallwng",label:"Welshpool / Y Trallwng"},
{value:"Welwyn Garden City",label:"Welwyn Garden City"},
{value:"Wem",label:"Wem"},
{value:"Wendover",label:"Wendover"},
{value:"West Bridgford",label:"West Bridgford"},
{value:"West Bromwich",label:"West Bromwich"},
{value:"Westbury",label:"Westbury"},
{value:"Westerham",label:"Westerham"},
{value:"Westhill",label:"Westhill"},
{value:"Westhoughton",label:"Westhoughton"},
{value:"West Kirby",label:"West Kirby"},
{value:"West Malling",label:"West Malling"},
{value:"West Mersea",label:"West Mersea"},
{value:"Westminster",label:"Westminster"},
{value:"Weston-Super-Mare",label:"Weston-Super-Mare"},
{value:"Wetherby",label:"Wetherby"},
{value:"Weybridge",label:"Weybridge"},
{value:"Weymouth",label:"Weymouth"},
{value:"Whaley Bridge",label:"Whaley Bridge"},
{value:"Whickham",label:"Whickham"},
{value:"Whitburn",label:"Whitburn"},
{value:"Whitburn",label:"Whitburn"},
{value:"Whitby",label:"Whitby"},
{value:"Whitchurch",label:"Whitchurch"},
{value:"Whitchurch",label:"Whitchurch"},
{value:"Whitefield",label:"Whitefield"},
{value:"Whitehaven",label:"Whitehaven"},
{value:"Whithorn",label:"Whithorn"},
{value:"Whitland / Hendy-Gwyn",label:"Whitland / Hendy-Gwyn"},
{value:"Whitley Bay",label:"Whitley Bay"},
{value:"Whitnash",label:"Whitnash"},
{value:"Whitstable",label:"Whitstable"},
{value:"Whittlesey",label:"Whittlesey"},
{value:"Whitworth",label:"Whitworth"},
{value:"Wick",label:"Wick"},
{value:"Wickford",label:"Wickford"},
{value:"Wickham",label:"Wickham"},
{value:"Wickham Market",label:"Wickham Market"},
{value:"Widnes",label:"Widnes"},
{value:"Wigan",label:"Wigan"},
{value:"Wigton",label:"Wigton"},
{value:"Wigtown",label:"Wigtown"},
{value:"Willenhall",label:"Willenhall"},
{value:"Willington",label:"Willington"},
{value:"Wilmslow",label:"Wilmslow"},
{value:"Wilton",label:"Wilton"},
{value:"Wimborne Minster",label:"Wimborne Minster"},
{value:"Wincanton",label:"Wincanton"},
{value:"Winchcombe",label:"Winchcombe"},
{value:"Winchester",label:"Winchester"},
{value:"Windermere",label:"Windermere"},
{value:"Windsor",label:"Windsor"},
{value:"Winsford",label:"Winsford"},
{value:"Winslow",label:"Winslow"},
{value:"Winterton",label:"Winterton"},
{value:"Wirksworth",label:"Wirksworth"},
{value:"Wisbech",label:"Wisbech"},
{value:"Wishaw",label:"Wishaw"},
{value:"Witham",label:"Witham"},
{value:"Withernsea",label:"Withernsea"},
{value:"Witney",label:"Witney"},
{value:"Wiveliscombe",label:"Wiveliscombe"},
{value:"Wivenhoe",label:"Wivenhoe"},
{value:"Woburn",label:"Woburn"},
{value:"Woburn Sands",label:"Woburn Sands"},
{value:"Woking",label:"Woking"},
{value:"Wokingham",label:"Wokingham"},
{value:"Wolsingham",label:"Wolsingham"},
{value:"Wolverhampton",label:"Wolverhampton"},
{value:"Wombwell",label:"Wombwell"},
{value:"Woodbridge",label:"Woodbridge"},
{value:"Woodhall Spa",label:"Woodhall Spa"},
{value:"Woodley",label:"Woodley"},
{value:"Woodstock",label:"Woodstock"},
{value:"Wooler",label:"Wooler"},
{value:"Worcester",label:"Worcester"},
{value:"Workington",label:"Workington"},
{value:"Worksop",label:"Worksop"},
{value:"Worsbrough",label:"Worsbrough"},
{value:"Worsley",label:"Worsley"},
{value:"Worthing",label:"Worthing"},
{value:"Wotton Cross",label:"Wotton Cross"},
{value:"Wotton-under-Edge",label:"Wotton-under-Edge"},
{value:"Wragby",label:"Wragby"},
{value:"Wrexham / Wrecsam",label:"Wrexham / Wrecsam"},
{value:"Wymondham",label:"Wymondham"},
{value:"Yarm",label:"Yarm"},
{value:"Yarmouth",label:"Yarmouth"},
{value:"Yate",label:"Yate"},
{value:"Yateley",label:"Yateley"},
{value:"Y Bala",label:"Y Bala"},
{value:"Yeadon",label:"Yeadon"},
{value:"Yeovil",label:"Yeovil"},
{value:"York",label:"York"},
{value:"Ystradgynlais",label:"Ystradgynlais"},
{value:"Ystrad Mynach",label:"Ystrad Mynach"},
{value:"Acton",label:"Acton"},
{value:"Alameda Place",label:"Alameda Place"},
{value:"Aperfield",label:"Aperfield"},
{value:"Barking",label:"Barking"},
{value:"Barnes",label:"Barnes"},
{value:"Barnet",label:"Barnet"},
{value:"Barnet Gate",label:"Barnet Gate"},
{value:"Battersea",label:"Battersea"},
{value:"Beckenham",label:"Beckenham"},
{value:"Bermondsey",label:"Bermondsey"},
{value:"Bethnal Green",label:"Bethnal Green"},
{value:"Bexley",label:"Bexley"},
{value:"Biggin Hill",label:"Biggin Hill"},
{value:"Bow",label:"Bow"},
{value:"Brentford",label:"Brentford"},
{value:"Bromley",label:"Bromley"},
{value:"Camberwell",label:"Camberwell"},
{value:"Camden Town",label:"Camden Town"},
{value:"Carshalton",label:"Carshalton"},
{value:"Catford",label:"Catford"},
{value:"Central Parade",label:"Central Parade"},
{value:"Chase Village",label:"Chase Village"},
{value:"Chelsea",label:"Chelsea"},
{value:"Chingford",label:"Chingford"},
{value:"Chislehurst",label:"Chislehurst"},
{value:"Chiswick",label:"Chiswick"},
{value:"Clapham",label:"Clapham"},
{value:"Clock House",label:"Clock House"},
{value:"Coalmakers Wharf",label:"Coalmakers Wharf"},
{value:"Coldharbour",label:"Coldharbour"},
{value:"Cole Park",label:"Cole Park"},
{value:"Colney Hatch",label:"Colney Hatch"},
{value:"Coulsdon",label:"Coulsdon"},
{value:"Cowley Peachy",label:"Cowley Peachy"},
{value:"Crayford",label:"Crayford"},
{value:"Croydon",label:"Croydon"},
{value:"Dagenham",label:"Dagenham"},
{value:"Denham",label:"Denham"},
{value:"Deptford",label:"Deptford"},
{value:"Ealing",label:"Ealing"},
{value:"Eastcote Village",label:"Eastcote Village"},
{value:"East Ham",label:"East Ham"},
{value:"Edgware",label:"Edgware"},
{value:"Edmonton",label:"Edmonton"},
{value:"Eltham",label:"Eltham"},
{value:"Enfield",label:"Enfield"},
{value:"Erith",label:"Erith"},
{value:"Feltham",label:"Feltham"},
{value:"Festubert Place",label:"Festubert Place"},
{value:"Finchley",label:"Finchley"},
{value:"Foxbury",label:"Foxbury"},
{value:"Frank Whipple Estate",label:"Frank Whipple Estate"},
{value:"Friern Barnet",label:"Friern Barnet"},
{value:"Fulham",label:"Fulham"},
{value:"Gallows Corner",label:"Gallows Corner"},
{value:"Greenford",label:"Greenford"},
{value:"Greenwich",label:"Greenwich"},
{value:"Hackney",label:"Hackney"},
{value:"Hacton",label:"Hacton"},
{value:"Hallsville Quarter",label:"Hallsville Quarter"},
{value:"Hammersmith",label:"Hammersmith"},
{value:"Hampstead",label:"Hampstead"},
{value:"Hampton",label:"Hampton"},
{value:"Harefield Grove",label:"Harefield Grove"},
{value:"Harrow",label:"Harrow"},
{value:"Hayes",label:"Hayes"},
{value:"Hayes Town",label:"Hayes Town"},
{value:"Hendon",label:"Hendon"},
{value:"Highwood Hill",label:"Highwood Hill"},
{value:"Hillingdon",label:"Hillingdon"},
{value:"Hitchin Square",label:"Hitchin Square"},
{value:"Holders Hill",label:"Holders Hill"},
{value:"Hornchurch",label:"Hornchurch"},
{value:"Hornsey",label:"Hornsey"},
{value:"Hornsey Vale",label:"Hornsey Vale"},
{value:"Hounslow",label:"Hounslow"},
{value:"Ilford",label:"Ilford"},
{value:"Isle of Dogs",label:"Isle of Dogs"},
{value:"Isleworth",label:"Isleworth"},
{value:"Islington",label:"Islington"},
{value:"Kensington",label:"Kensington"},
{value:"Kenton",label:"Kenton"},
{value:"Kingston upon Thames",label:"Kingston upon Thames"},
{value:"Knight's Hill",label:"Knight's Hill"},
{value:"Lewisham",label:"Lewisham"},
{value:"Leyton",label:"Leyton"},
{value:"Merton",label:"Merton"},
{value:"Mitcham",label:"Mitcham"},
{value:"Morden",label:"Morden"},
{value:"New Cross Gate",label:"New Cross Gate"},
{value:"New Malden",label:"New Malden"},
{value:"Northolt",label:"Northolt"},
{value:"Northwood",label:"Northwood"},
{value:"Orpington",label:"Orpington"},
{value:"Paddington",label:"Paddington"},
{value:"Park Royal",label:"Park Royal"},
{value:"Penge",label:"Penge"},
{value:"Pinner",label:"Pinner"},
{value:"Poplar",label:"Poplar"},
{value:"Poynders Parade",label:"Poynders Parade"},
{value:"Purley",label:"Purley"},
{value:"Putney",label:"Putney"},
{value:"Rainham",label:"Rainham"},
{value:"Risley Close",label:"Risley Close"},
{value:"Romford",label:"Romford"},
{value:"Ruislip",label:"Ruislip"},
{value:"Ruislip Gardens",label:"Ruislip Gardens"},
{value:"Rushmore Hill",label:"Rushmore Hill"},
{value:"Sidcup",label:"Sidcup"},
{value:"Southall",label:"Southall"},
{value:"South Bromley",label:"South Bromley"},
{value:"Southgate",label:"Southgate"},
{value:"Southwark",label:"Southwark"},
{value:"Stanmore",label:"Stanmore"},
{value:"Stepney",label:"Stepney"},
{value:"Stoke Newington",label:"Stoke Newington"},
{value:"Stratford",label:"Stratford"},
{value:"Streatham",label:"Streatham"},
{value:"Surbiton",label:"Surbiton"},
{value:"Sutton",label:"Sutton"},
{value:"Tavern Quay",label:"Tavern Quay"},
{value:"Teddington",label:"Teddington"},
{value:"The Mews",label:"The Mews"},
{value:"Tottenham",label:"Tottenham"},
{value:"Tower Gardens",label:"Tower Gardens"},
{value:"Trinity Buoy Wharf",label:"Trinity Buoy Wharf"},
{value:"Twickenham",label:"Twickenham"},
{value:"Unity Place",label:"Unity Place"},
{value:"Upminster",label:"Upminster"},
{value:"Uxbridge",label:"Uxbridge"},
{value:"Wallington",label:"Wallington"},
{value:"Wallington Square",label:"Wallington Square"},
{value:"Walthamstow",label:"Walthamstow"},
{value:"Wandle Park",label:"Wandle Park"},
{value:"Wandsworth",label:"Wandsworth"},
{value:"Wanstead",label:"Wanstead"},
{value:"Wembley",label:"Wembley"},
{value:"West Drayton",label:"West Drayton"},
{value:"West Ham",label:"West Ham"},
{value:"Willesden",label:"Willesden"},
{value:"Wimbledon",label:"Wimbledon"},
{value:"Woodford",label:"Woodford"},
{value:"Wood Green",label:"Wood Green"},
{value:"Woolwich",label:"Woolwich"},
{value:"Yiewsley",label:"Yiewsley"},
{value:"Unknown",label:"Unknown"},
];

  module.exports = ukCitiesAndTowns;
