'use strict'

const ukRegions = [
{value:"Aberdeenshire",label:"Aberdeenshire"},
{value:"Angus",label:"Angus"},
{value:"Argyll and Bute",label:"Argyll and Bute"},
{value:"Ayrshire and Arran",label:"Ayrshire and Arran"},
{value:"Banffshire",label:"Banffshire"},
{value:"Bedfordshire",label:"Bedfordshire"},
{value:"Berkshire",label:"Berkshire"},
{value:"Berwickshire",label:"Berwickshire"},
{value:"Bristol",label:"Bristol"},
{value:"Buckinghamshire",label:"Buckinghamshire"},
{value:"Caithness",label:"Caithness"},
{value:"Cambridgeshire",label:"Cambridgeshire"},
{value:"Cheshire",label:"Cheshire"},
{value:"City of Aberdeen",label:"City of Aberdeen"},
{value:"City of Dundee",label:"City of Dundee"},
{value:"City of Edinburgh",label:"City of Edinburgh"},
{value:"City of Glasgow",label:"City of Glasgow"},
{value:"Clackmannan",label:"Clackmannan"},
{value:"Clwyd",label:"Clwyd"},
{value:"Cornwall",label:"Cornwall"},
{value:"County Antrim",label:"County Antrim"},
{value:"County Armagh",label:"County Armagh"},
{value:"County Derry / Londonderry",label:"County Derry / Londonderry"},
{value:"County Down",label:"County Down"},
{value:"County Fermanagh",label:"County Fermanagh"},
{value:"County Tyrone",label:"County Tyrone"},
{value:"Cumbria",label:"Cumbria"},
{value:"Derbyshire",label:"Derbyshire"},
{value:"Devon",label:"Devon"},
{value:"Dorset",label:"Dorset"},
{value:"Dumfries",label:"Dumfries"},
{value:"Dunbartonshire",label:"Dunbartonshire"},
{value:"Durham",label:"Durham"},
{value:"Dyfed",label:"Dyfed"},
{value:"East Lothian",label:"East Lothian"},
{value:"East Riding of Yorkshire",label:"East Riding of Yorkshire"},
{value:"East Sussex",label:"East Sussex"},
{value:"Essex",label:"Essex"},
{value:"Fife",label:"Fife"},
{value:"Gloucestershire",label:"Gloucestershire"},
{value:"Greater London",label:"Greater London"},
{value:"Greater Manchester",label:"Greater Manchester"},
{value:"Gwent",label:"Gwent"},
{value:"Gwynedd",label:"Gwynedd"},
{value:"Hampshire",label:"Hampshire"},
{value:"Herefordshire",label:"Herefordshire"},
{value:"Hertfordshire",label:"Hertfordshire"},
{value:"Inverness",label:"Inverness"},
{value:"Isle of Man",label:"Isle of Man"},
{value:"Isle of Wight",label:"Isle of Wight"},
{value:"Kent",label:"Kent"},
{value:"Kincardineshire",label:"Kincardineshire"},
{value:"Lanarkshire",label:"Lanarkshire"},
{value:"Lancashire",label:"Lancashire"},
{value:"Leicestershire",label:"Leicestershire"},
{value:"Lincolnshire",label:"Lincolnshire"},
{value:"Merseyside",label:"Merseyside"},
{value:"Mid Glamorgan",label:"Mid Glamorgan"},
{value:"Midlothian",label:"Midlothian"},
{value:"Moray",label:"Moray"},
{value:"Nairn",label:"Nairn"},
{value:"Norfolk",label:"Norfolk"},
{value:"North Yorkshire",label:"North Yorkshire"},
{value:"Northamptonshire",label:"Northamptonshire"},
{value:"Northumberland",label:"Northumberland"},
{value:"Nottinghamshire",label:"Nottinghamshire"},
{value:"Orkney",label:"Orkney"},
{value:"Oxfordshire",label:"Oxfordshire"},
{value:"Perth and Kinross",label:"Perth and Kinross"},
{value:"Powys",label:"Powys"},
{value:"Renfrewshire",label:"Renfrewshire"},
{value:"Ross and Cromarty",label:"Ross and Cromarty"},
{value:"Roxburgh, Ettrick and Lauderdale",label:"Roxburgh, Ettrick and Lauderdale"},
{value:"Rutland",label:"Rutland"},
{value:"Shetland",label:"Shetland"},
{value:"Shropshire",label:"Shropshire"},
{value:"Somerset",label:"Somerset"},
{value:"South Glamorgan",label:"South Glamorgan"},
{value:"South Yorkshire",label:"South Yorkshire"},
{value:"Staffordshire",label:"Staffordshire"},
{value:"Stirling and Falkirk",label:"Stirling and Falkirk"},
{value:"Suffolk",label:"Suffolk"},
{value:"Surrey",label:"Surrey"},
{value:"Sutherland",label:"Sutherland"},
{value:"The Stewartry of Kirkcudbright",label:"The Stewartry of Kirkcudbright"},
{value:"Tweeddale",label:"Tweeddale"},
{value:"Tyne and Wear",label:"Tyne and Wear"},
{value:"Warwickshire",label:"Warwickshire"},
{value:"West Glamorgan",label:"West Glamorgan"},
{value:"West Lothian",label:"West Lothian"},
{value:"West Midlands",label:"West Midlands"},
{value:"West Sussex",label:"West Sussex"},
{value:"West Yorkshire",label:"West Yorkshire"},
{value:"Western Isles",label:"Western Isles"},
{value:"Wigtown",label:"Wigtown"},
{value:"Wiltshire",label:"Wiltshire"},
{value:"Worcestershire",label:"Worcestershire"},
{value:"Unknown",label:"Unknown"},
];


module.exports = ukRegions;
