pipeline:

  build_8:
    image: node:8
    commands:
      - npm --loglevel warn install
      - npm run test
    when:
      event: [push, pull_request]

  build_app_pr:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t app-$${DRONE_COMMIT_SHA} .
    when:
      event: pull_request

  build_app:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t app-$${DRONE_COMMIT_SHA} .
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+modern_slavery_bot
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/modern-slavery
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push

  tag_to_quay:
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+modern_slavery_bot
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/modern-slavery
    secrets: 
      - docker_password
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
