pipeline:
  # Runs unit tests & eslint only
  build_8:
    image: node:8
    commands:
      - npm --loglevel warn install
      - npm run test
    when:
      event:
        - push
        - pull_request

  # Run acceptance tests using docker-compose only
  # Run this on pull_requests
  acceptance_test:
    image: docker/compose:1.23.2
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker-compose --verbose up -d --build chrome-browser app redis
      - docker-compose exec -T app sh -c 'npm run test:docker-acceptance'
    when:
      event:
        - pull_request

  # Run acceptance tests using docker-compose only
  # Run it on master branch as well
  acceptance_test:
    image: docker/compose:1.23.2
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker-compose --verbose up -d --build chrome-browser app redis
      - docker-compose exec -T app sh -c 'npm run test:docker-acceptance'
    when:
      branch: master
      event: push

  build_app:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t app-$${DRONE_COMMIT_SHA} .
    when:
      branch: master
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+modern_slavery_bot
    registry: quay.io
    branch: master
    repo: quay.io/ukhomeofficedigital/modern-slavery
    tags:
      - ${DRONE_COMMIT_SHA}
      - build-${DRONE_BUILD_NUMBER}
      - latest
    when:
      branch: master
      event: push

    trigger_deploy_to_dev:
      image: quay.io/ukhomeofficedigital/drone-trigger:v0.3.0
      drone_server: https://drone-gitlab.acp.homeoffice.gov.uk
      repo: modern-slavery/kube-modern-slavery
      secrets:
        - drone_token
      branch: master
      deploy_to: dev
      params: "VERSION=${DRONE_COMMIT_SHA}"
      when:
        branch: master
        event: push

  tag_to_quay:
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+modern_slavery_bot
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/modern-slavery
    secrets:
      - docker_password
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
