pipeline:

  build_8:
    image: node:8
    commands:
      - npm --loglevel warn install
      - npm run test
    when:
      event: [push, pull_request]

  build_app:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t app-$${DRONE_COMMIT_SHA} .
    when:
      event: pull_request

  build_app:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t app-$${DRONE_COMMIT_SHA} .
    when:
      branch: master
      event: push
