version: "2"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile-acceptance
    environment:
      - ALLOW_SKIP=true
      - SKIP_EMAIL=sas-hof-test@digital.homeoffice.gov.uk
      - NODE_ENV=local
      - IGNORE_TLS=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CASEWORKER_EMAIL=sas-hof-test@digital.homeoffice.gov.uk
    links:
      - redis
      - chrome-browser:chrome
    ports:
      - "8081:8081"
    volumes:
      - "/app/public"
    user: nodejs
    container_name: modern-slavery-app

  chrome-browser:
    build: ./browsers/chrome
    shm_size: '1gb'
    cap_add:
      - SYS_ADMIN
    ports:
      - '9222:9222'
    volumes:
      - ./acceptance-test/user-pathways/upload-file/images:/app/public/images
    container_name: modern-slavery-chrome-browser

  redis:
    image: redis
    container_name: modern-slavery-redis

  nginx-proxy:
    image: quay.io/ukhomeofficedigital/nginx-proxy:v3
    environment:
      - PROXY_SERVICE_HOST=app
      - PROXY_SERVICE_PORT=8081
      - NAXSI_USE_DEFAULT_RULES=FALSE
      - ERROR_REDIRECT_CODES=599
    ports:
      - "443:10443"
      - "80:10080"
    links:
      - app

  zap:
    image: owasp/zap2docker-stable
    environment:
      ZAP_PROXY: 8090
    ports:
      - "8090:8090"
    expose:
      - "8090"
    links:
      - app
    command: 'zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config anticsrf.tokens.token.name=x-csrf-token'
    #volumes:
    #  - ${PWD}/zap:/home/zap:rw