version: "2"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile-acceptance
    environment:
      - allowSkip=true
      - IGNORE_TLS=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CASEWORKER_EMAIL=sas-hof-test@digital.homeoffice.gov.uk
    links:
      - redis
      - chrome-browser:chrome
    ports:
      - "8081:8081"
    volumes:
      - "/app/public"
    user: nodejs
    container_name: modern-slavery-app

  chrome-browser:
    build: ./browsers/chrome
    shm_size: '1gb'
    cap_add:
      - SYS_ADMIN
    ports:
      - '9222:9222'
    volumes:
      - ./acceptance-test/user-pathways/upload-file/images:/app/public/images
    container_name: modern-slavery-chrome-browser

  redis:
    image: redis
    container_name: modern-slavery-redis

  nginx-proxy:
    image: quay.io/ukhomeofficedigital/nginx-proxy:v3
    environment:
      - PROXY_SERVICE_HOST=app
      - PROXY_SERVICE_PORT=8081
      - NAXSI_USE_DEFAULT_RULES=FALSE
      - ERROR_REDIRECT_CODES=599
    ports:
      - "443:10443"
      - "80:10080"
    links:
      - app
