---
apiVersion: v1
kind: Service
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: lookup-{{ .DRONE_SOURCE_BRANCH }}
  labels:
    name: lookup-{{ .DRONE_SOURCE_BRANCH }}
    role: service-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: lookup
  labels:
    name: lookup
    role: service
  {{ end }}
spec:
  selector:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    name: lookup-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    name: lookup
    {{ end }}
  ports:
  - name: http
    port: 10080
  - name: https
    port: 10443
