---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: ingress-internal-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: ingress-internal
  {{ end }}
  {{ if not (eq .KUBE_NAMESPACE .BRANCH_ENV) }}
  labels:
    cert-manager.io/solver: route53
  {{ end }}
  annotations:
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/proxy-body-size: "200m"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    {{ if or (eq .KUBE_NAMESPACE .STG_ENV) (eq .KUBE_NAMESPACE .PROD_ENV) }}
    kubernetes.io/ingress.class: "nginx-internal"
    {{ end }}
    {{ if not (eq .KUBE_NAMESPACE .BRANCH_ENV) }}
    cert-manager.io/enabled: "true"
    {{ end }}
spec:
  tls:
    - hosts:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        - {{ .DRONE_BUILD_NUMBER }}.internal.{{ .BRANCH_ENV }}.homeoffice.gov.uk
        - ms-{{ .DRONE_SOURCE_BRANCH }}.internal.{{ .BRANCH_ENV }}.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
        - uat.internal.ms-notprod.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
        - preprod.internal.ms-notprod.homeoffice.gov.uk
      {{ end }}
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      secretName: branch-tls-internal
      {{ else }}
      secretName: ingress-internal
      {{ end }}
  rules:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    - host: ms-{{ .DRONE_SOURCE_BRANCH }}.internal.{{ .BRANCH_ENV }}.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
    - host: uat.internal.ms-notprod.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
    - host: preprod.internal.ms-notprod.homeoffice.gov.uk
    {{ end }}
      http:
        paths:
          - path: /
            backend:
              {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
              serviceName: modern-slavery-main-{{ .DRONE_SOURCE_BRANCH }}
              {{ else }}
              serviceName: modern-slavery-main
              {{ end }}
              servicePort: 10443
