apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: app-allow-ingress-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: app-allow-ingress
  {{ end }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-external
    ports:
    - port: 10080
      protocol: TCP
    - port: 10443
      protocol: TCP
  podSelector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      name: app-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      name: app
      {{ end }}
  policyTypes:
  - Ingress
