---
apiVersion: v1
kind: Service
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: app-{{ .DRONE_SOURCE_BRANCH }}
  labels:
    name: app-{{ .DRONE_SOURCE_BRANCH }}
    role: service-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: app
  labels:
    name: app
    role: service
  {{ end }}
spec:
  selector:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    name: app-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    name: app
    {{ end }}
  type: ClusterIP
  ports:
  - name: http
    port: 10080
  - name: https
    port: 10443
