apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: tls
spec:
  secretName: tls
  issuerRef:
    name: platform-ca
    kind: ClusterIssuer
  dnsNames:
  - modern-slavery-main
  - modern-slavery-main.ms-dev
  - modern-slavery-main.ms-dev.svc
  - modern-slavery-main.ms-dev.svc.cluster.local
  - localhost
  ipAddresses:
  - 127.0.0.1