---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
  name: redis
  {{ else if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  annotations:
    downscaler/uptime: {{ .NON_PROD_AVAILABILITY }}
  name: redis-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  annotations:
    downscaler/uptime: {{ .NON_PROD_AVAILABILITY }}
  name: redis
  {{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      name: redis-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      name: redis
      {{ end }}
  template:
    metadata:
      labels:
        {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        name: redis-{{ .DRONE_SOURCE_BRANCH }}
        service: redis-{{ .DRONE_SOURCE_BRANCH }}
        {{ else }}
        name: redis
        service: redis
        {{ end }}
    spec:
      containers:
        - name: redis
          # redis:v5.0.6-1
          image: quay.io/ukhomeofficedigital/redis@sha256:4499ea7306de776dab2ba8befd723a419fd311519d6f91f7821ed1a7c589da3b
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /var/lib/redis
              name: data
            - mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
               name: redis-config
          volumes:
            - name: redis-config
              configMap:
                name: redis-config
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              cpu: "256m"
              memory: "512Mi"
            limits:
              cpu: "512m"
              memory: "2Gi"
      volumes:
        - name: data
          emptyDir: {}
