apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: redis-permit-access-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: redis-permit-access
  {{ end }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
          name: modern-slavery-main-{{ .DRONE_SOURCE_BRANCH }}
          {{ else }}
          name: modern-slavery-main
          {{ end }}
    - podSelector:
        matchLabels:
          {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
          name: lookup-{{ .DRONE_SOURCE_BRANCH }}
          {{ else }}
          name: lookup
          {{ end }}
    ports:
    - port: 6379
      protocol: TCP
  podSelector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      name: redis-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      name: redis
      {{ end }}
