// Generated from: e2e-tests/features/nrm/nrm.feature
import { test } from "../../../../e2e-tests/fixtures/test-fixtures.js";

test.describe('NRM - National Referral Mechanism', () => {

  test.beforeEach('Background', async ({ Given, nrmTestDataRepository }, testInfo) => { if (testInfo.error) return;
    await Given('Test data has been created for "NRM" scenarios', null, { nrmTestDataRepository }); 
  });
  
  test.describe('National Referral Mechanism - E2E', () => {

    test('Example #1', { tag: ['@nrm', '@NrmRegression', '@RegressionTestCI', '@regression3', '@nrm-full-flow'] }, async ({ Given, When, Then, And, nrmJourneyContext, nrmPages, nrmTestDataRepository }) => { 
      await Given('I selected the data for scenario "1" - "\'Yes\' answers - under18"', null, { nrmJourneyContext, nrmTestDataRepository }); 
      await When('I visit the National Referral Mechanism page', null, { nrmPages }); 
      await And('I enter my work Email "sas-hof-test@digital.homeoffice.gov.uk" and create new report - check error "No"', null, { nrmJourneyContext, nrmPages }); 
      await And('I fill out my answers to the NRM questionnaire - check error "No"', null, { nrmJourneyContext, nrmPages }); 
      await Then('I am able to submit the NRM questionnaire', null, { nrmPages }); 
    });

    test('Example #2', { tag: ['@nrm', '@NrmRegression', '@RegressionTestCI', '@regression3', '@nrm-full-flow'] }, async ({ Given, When, Then, And, nrmJourneyContext, nrmPages, nrmTestDataRepository }) => { 
      await Given('I selected the data for scenario "2" - "\'No\' answers - over18, No Cooperation"', null, { nrmJourneyContext, nrmTestDataRepository }); 
      await When('I visit the National Referral Mechanism page', null, { nrmPages }); 
      await And('I enter my work Email "sas-hof-test@digital.homeoffice.gov.uk" and create new report - check error "No"', null, { nrmJourneyContext, nrmPages }); 
      await And('I fill out my answers to the NRM questionnaire - check error "No"', null, { nrmJourneyContext, nrmPages }); 
      await Then('I am able to submit the NRM questionnaire', null, { nrmPages }); 
    });

    test('Example #3', { tag: ['@nrm', '@NrmRegression', '@RegressionTestCI', '@regression3', '@nrm-full-flow'] }, async ({ Given, When, Then, And, nrmJourneyContext, nrmPages, nrmTestDataRepository }) => { 
      await Given('I selected the data for scenario "5" - "Not sure if under18"', null, { nrmJourneyContext, nrmTestDataRepository }); 
      await When('I visit the National Referral Mechanism page', null, { nrmPages }); 
      await And('I enter my work Email "sas-hof-test@digital.homeoffice.gov.uk" and create new report - check error "No"', null, { nrmJourneyContext, nrmPages }); 
      await And('I fill out my answers to the NRM questionnaire - check error "No"', null, { nrmJourneyContext, nrmPages }); 
      await Then('I am able to submit the NRM questionnaire', null, { nrmPages }); 
    });

    test('Example #4', { tag: ['@nrm', '@NrmRegression', '@RegressionTestCI', '@regression3', '@nrm-full-flow'] }, async ({ Given, When, Then, And, nrmJourneyContext, nrmPages, nrmTestDataRepository }) => { 
      await Given('I selected the data for scenario "6" - "E2E mixed"', null, { nrmJourneyContext, nrmTestDataRepository }); 
      await When('I visit the National Referral Mechanism page', null, { nrmPages }); 
      await And('I enter my work Email "sas-hof-test@digital.homeoffice.gov.uk" and create new report - check error "No"', null, { nrmJourneyContext, nrmPages }); 
      await And('I fill out my answers to the NRM questionnaire - check error "No"', null, { nrmJourneyContext, nrmPages }); 
      await Then('I am able to submit the NRM questionnaire', null, { nrmPages }); 
    });

    test('Example #5', { tag: ['@nrm', '@NrmRegression', '@RegressionTestCI', '@regression3', '@nrm-full-flow'] }, async ({ Given, When, Then, And, nrmJourneyContext, nrmPages, nrmTestDataRepository }) => { 
      await Given('I selected the data for scenario "8" - "Add max locations"', null, { nrmJourneyContext, nrmTestDataRepository }); 
      await When('I visit the National Referral Mechanism page', null, { nrmPages }); 
      await And('I enter my work Email "sas-hof-test@digital.homeoffice.gov.uk" and create new report - check error "No"', null, { nrmJourneyContext, nrmPages }); 
      await And('I fill out my answers to the NRM questionnaire - check error "No"', null, { nrmJourneyContext, nrmPages }); 
      await Then('I am able to submit the NRM questionnaire', null, { nrmPages }); 
    });

    test('Example #6', { tag: ['@nrm', '@NrmRegression', '@RegressionTestCI', '@regression3', '@nrm-full-flow'] }, async ({ Given, When, Then, And, nrmJourneyContext, nrmPages, nrmTestDataRepository }) => { 
      await Given('I selected the data for scenario "9" - "\'No\' answers - Yes Cooperation"', null, { nrmJourneyContext, nrmTestDataRepository }); 
      await When('I visit the National Referral Mechanism page', null, { nrmPages }); 
      await And('I enter my work Email "sas-hof-test@digital.homeoffice.gov.uk" and create new report - check error "No"', null, { nrmJourneyContext, nrmPages }); 
      await And('I fill out my answers to the NRM questionnaire - check error "No"', null, { nrmJourneyContext, nrmPages }); 
      await Then('I am able to submit the NRM questionnaire', null, { nrmPages }); 
    });

  });

  test('NRM - Continue report', { tag: ['@nrm', '@NrmRegression', '@nrm-continue-report'] }, async ({ Given, When, Then, And, nrmJourneyContext, nrmPages, nrmTestDataRepository }) => { 
    await Given('I selected the data for scenario "3" - "Continue report"', null, { nrmJourneyContext, nrmTestDataRepository }); 
    await When('I visit the National Referral Mechanism page', null, { nrmPages }); 
    await And('I enter my work Email "sas-hof-test@digital.homeoffice.gov.uk" and create new report - check error "No"', null, { nrmJourneyContext, nrmPages }); 
    await And('I fill out my answers to some of the NRM questionnaire - check error "No"', null, { nrmJourneyContext, nrmPages }); 
    await And('I navigate back to the reports dashboard', null, { nrmPages }); 
    await Then('I am able to click \'Go to report\' button and continue the report', null, { nrmJourneyContext, nrmPages }); 
  });

  test('NRM - Delete report', { tag: ['@nrm', '@NrmRegression', '@nrm-delete-report'] }, async ({ Given, When, Then, And, nrmJourneyContext, nrmPages, nrmTestDataRepository }) => { 
    await Given('I selected the data for scenario "4" - "Delete report"', null, { nrmJourneyContext, nrmTestDataRepository }); 
    await When('I visit the National Referral Mechanism page', null, { nrmPages }); 
    await And('I enter my work Email "sas-hof-test@digital.homeoffice.gov.uk" and create new report - check error "No"', null, { nrmJourneyContext, nrmPages }); 
    await And('I fill out my answers to some of the NRM questionnaire - check error "No"', null, { nrmJourneyContext, nrmPages }); 
    await And('I navigate back to the reports dashboard', null, { nrmPages }); 
    await Then('I am able to delete my report', null, { nrmJourneyContext, nrmPages }); 
  });

  test('NRM - Save And Exit report', { tag: ['@nrm', '@NrmRegression', '@nrm-save-and-exit-report'] }, async ({ Given, When, Then, And, nrmJourneyContext, nrmPages, nrmTestDataRepository }) => { 
    await Given('I selected the data for scenario "11" - "Save and exit report"', null, { nrmJourneyContext, nrmTestDataRepository }); 
    await When('I visit the National Referral Mechanism page', null, { nrmPages }); 
    await And('I enter my work Email "sas-hof-test@digital.homeoffice.gov.uk" and create new report - check error "No"', null, { nrmJourneyContext, nrmPages }); 
    await And('I fill out my answers to some of the NRM questionnaire - check error "No"', null, { nrmJourneyContext, nrmPages }); 
    await Then('I click \'Save and exit\' button and confirm my report is saved', null, { nrmPages }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('e2e-tests/features/nrm/nrm.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":18,"tags":["@nrm","@NrmRegression","@RegressionTestCI","@regression3","@nrm-full-flow"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"NRM\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"NRM\"","children":[{"start":32,"value":"NRM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"1\" - \"'Yes' answers - under18\"","stepMatchArguments":[{"group":{"start":33,"value":"\"1\"","children":[{"start":34,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"'Yes' answers - under18\"","children":[{"start":40,"value":"'Yes' answers - under18","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"When I visit the National Referral Mechanism page","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And I enter my work Email \"sas-hof-test@digital.homeoffice.gov.uk\" and create new report - check error \"No\"","stepMatchArguments":[{"group":{"start":22,"value":"\"sas-hof-test@digital.homeoffice.gov.uk\"","children":[{"start":23,"value":"sas-hof-test@digital.homeoffice.gov.uk","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":99,"value":"\"No\"","children":[{"start":100,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":16,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"And I fill out my answers to the NRM questionnaire - check error \"No\"","stepMatchArguments":[{"group":{"start":61,"value":"\"No\"","children":[{"start":62,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":17,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then I am able to submit the NRM questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":20,"pickleLine":19,"tags":["@nrm","@NrmRegression","@RegressionTestCI","@regression3","@nrm-full-flow"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"NRM\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"NRM\"","children":[{"start":32,"value":"NRM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"2\" - \"'No' answers - over18, No Cooperation\"","stepMatchArguments":[{"group":{"start":33,"value":"\"2\"","children":[{"start":34,"value":"2","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"'No' answers - over18, No Cooperation\"","children":[{"start":40,"value":"'No' answers - over18, No Cooperation","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"When I visit the National Referral Mechanism page","stepMatchArguments":[]},{"pwStepLine":23,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And I enter my work Email \"sas-hof-test@digital.homeoffice.gov.uk\" and create new report - check error \"No\"","stepMatchArguments":[{"group":{"start":22,"value":"\"sas-hof-test@digital.homeoffice.gov.uk\"","children":[{"start":23,"value":"sas-hof-test@digital.homeoffice.gov.uk","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":99,"value":"\"No\"","children":[{"start":100,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":24,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"And I fill out my answers to the NRM questionnaire - check error \"No\"","stepMatchArguments":[{"group":{"start":61,"value":"\"No\"","children":[{"start":62,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":25,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then I am able to submit the NRM questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":28,"pickleLine":20,"tags":["@nrm","@NrmRegression","@RegressionTestCI","@regression3","@nrm-full-flow"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"NRM\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"NRM\"","children":[{"start":32,"value":"NRM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":29,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"5\" - \"Not sure if under18\"","stepMatchArguments":[{"group":{"start":33,"value":"\"5\"","children":[{"start":34,"value":"5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Not sure if under18\"","children":[{"start":40,"value":"Not sure if under18","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"When I visit the National Referral Mechanism page","stepMatchArguments":[]},{"pwStepLine":31,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And I enter my work Email \"sas-hof-test@digital.homeoffice.gov.uk\" and create new report - check error \"No\"","stepMatchArguments":[{"group":{"start":22,"value":"\"sas-hof-test@digital.homeoffice.gov.uk\"","children":[{"start":23,"value":"sas-hof-test@digital.homeoffice.gov.uk","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":99,"value":"\"No\"","children":[{"start":100,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"And I fill out my answers to the NRM questionnaire - check error \"No\"","stepMatchArguments":[{"group":{"start":61,"value":"\"No\"","children":[{"start":62,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then I am able to submit the NRM questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":36,"pickleLine":21,"tags":["@nrm","@NrmRegression","@RegressionTestCI","@regression3","@nrm-full-flow"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"NRM\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"NRM\"","children":[{"start":32,"value":"NRM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"6\" - \"E2E mixed\"","stepMatchArguments":[{"group":{"start":33,"value":"\"6\"","children":[{"start":34,"value":"6","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"E2E mixed\"","children":[{"start":40,"value":"E2E mixed","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"When I visit the National Referral Mechanism page","stepMatchArguments":[]},{"pwStepLine":39,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And I enter my work Email \"sas-hof-test@digital.homeoffice.gov.uk\" and create new report - check error \"No\"","stepMatchArguments":[{"group":{"start":22,"value":"\"sas-hof-test@digital.homeoffice.gov.uk\"","children":[{"start":23,"value":"sas-hof-test@digital.homeoffice.gov.uk","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":99,"value":"\"No\"","children":[{"start":100,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":40,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"And I fill out my answers to the NRM questionnaire - check error \"No\"","stepMatchArguments":[{"group":{"start":61,"value":"\"No\"","children":[{"start":62,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":41,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then I am able to submit the NRM questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":44,"pickleLine":22,"tags":["@nrm","@NrmRegression","@RegressionTestCI","@regression3","@nrm-full-flow"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"NRM\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"NRM\"","children":[{"start":32,"value":"NRM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"8\" - \"Add max locations\"","stepMatchArguments":[{"group":{"start":33,"value":"\"8\"","children":[{"start":34,"value":"8","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Add max locations\"","children":[{"start":40,"value":"Add max locations","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":46,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"When I visit the National Referral Mechanism page","stepMatchArguments":[]},{"pwStepLine":47,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And I enter my work Email \"sas-hof-test@digital.homeoffice.gov.uk\" and create new report - check error \"No\"","stepMatchArguments":[{"group":{"start":22,"value":"\"sas-hof-test@digital.homeoffice.gov.uk\"","children":[{"start":23,"value":"sas-hof-test@digital.homeoffice.gov.uk","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":99,"value":"\"No\"","children":[{"start":100,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":48,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"And I fill out my answers to the NRM questionnaire - check error \"No\"","stepMatchArguments":[{"group":{"start":61,"value":"\"No\"","children":[{"start":62,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":49,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then I am able to submit the NRM questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":52,"pickleLine":23,"tags":["@nrm","@NrmRegression","@RegressionTestCI","@regression3","@nrm-full-flow"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"NRM\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"NRM\"","children":[{"start":32,"value":"NRM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":53,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"9\" - \"'No' answers - Yes Cooperation\"","stepMatchArguments":[{"group":{"start":33,"value":"\"9\"","children":[{"start":34,"value":"9","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"'No' answers - Yes Cooperation\"","children":[{"start":40,"value":"'No' answers - Yes Cooperation","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":54,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"When I visit the National Referral Mechanism page","stepMatchArguments":[]},{"pwStepLine":55,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And I enter my work Email \"sas-hof-test@digital.homeoffice.gov.uk\" and create new report - check error \"No\"","stepMatchArguments":[{"group":{"start":22,"value":"\"sas-hof-test@digital.homeoffice.gov.uk\"","children":[{"start":23,"value":"sas-hof-test@digital.homeoffice.gov.uk","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":99,"value":"\"No\"","children":[{"start":100,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":56,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"And I fill out my answers to the NRM questionnaire - check error \"No\"","stepMatchArguments":[{"group":{"start":61,"value":"\"No\"","children":[{"start":62,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":57,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then I am able to submit the NRM questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":62,"pickleLine":26,"tags":["@nrm","@NrmRegression","@nrm-continue-report"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"NRM\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"NRM\"","children":[{"start":32,"value":"NRM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":63,"gherkinStepLine":27,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"3\" - \"Continue report\"","stepMatchArguments":[{"group":{"start":33,"value":"\"3\"","children":[{"start":34,"value":"3","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Continue report\"","children":[{"start":40,"value":"Continue report","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":64,"gherkinStepLine":28,"keywordType":"Action","textWithKeyword":"When I visit the National Referral Mechanism page","stepMatchArguments":[]},{"pwStepLine":65,"gherkinStepLine":29,"keywordType":"Action","textWithKeyword":"And I enter my work Email \"sas-hof-test@digital.homeoffice.gov.uk\" and create new report - check error \"No\"","stepMatchArguments":[{"group":{"start":22,"value":"\"sas-hof-test@digital.homeoffice.gov.uk\"","children":[{"start":23,"value":"sas-hof-test@digital.homeoffice.gov.uk","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":99,"value":"\"No\"","children":[{"start":100,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":66,"gherkinStepLine":30,"keywordType":"Action","textWithKeyword":"And I fill out my answers to some of the NRM questionnaire - check error \"No\"","stepMatchArguments":[{"group":{"start":69,"value":"\"No\"","children":[{"start":70,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"And I navigate back to the reports dashboard","stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then I am able to click 'Go to report' button and continue the report","stepMatchArguments":[]}]},
  {"pwTestLine":71,"pickleLine":35,"tags":["@nrm","@NrmRegression","@nrm-delete-report"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"NRM\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"NRM\"","children":[{"start":32,"value":"NRM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":72,"gherkinStepLine":36,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"4\" - \"Delete report\"","stepMatchArguments":[{"group":{"start":33,"value":"\"4\"","children":[{"start":34,"value":"4","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Delete report\"","children":[{"start":40,"value":"Delete report","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":73,"gherkinStepLine":37,"keywordType":"Action","textWithKeyword":"When I visit the National Referral Mechanism page","stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":38,"keywordType":"Action","textWithKeyword":"And I enter my work Email \"sas-hof-test@digital.homeoffice.gov.uk\" and create new report - check error \"No\"","stepMatchArguments":[{"group":{"start":22,"value":"\"sas-hof-test@digital.homeoffice.gov.uk\"","children":[{"start":23,"value":"sas-hof-test@digital.homeoffice.gov.uk","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":99,"value":"\"No\"","children":[{"start":100,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":75,"gherkinStepLine":39,"keywordType":"Action","textWithKeyword":"And I fill out my answers to some of the NRM questionnaire - check error \"No\"","stepMatchArguments":[{"group":{"start":69,"value":"\"No\"","children":[{"start":70,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":76,"gherkinStepLine":40,"keywordType":"Action","textWithKeyword":"And I navigate back to the reports dashboard","stepMatchArguments":[]},{"pwStepLine":77,"gherkinStepLine":41,"keywordType":"Outcome","textWithKeyword":"Then I am able to delete my report","stepMatchArguments":[]}]},
  {"pwTestLine":80,"pickleLine":44,"tags":["@nrm","@NrmRegression","@nrm-save-and-exit-report"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"NRM\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"NRM\"","children":[{"start":32,"value":"NRM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":81,"gherkinStepLine":45,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"11\" - \"Save and exit report\"","stepMatchArguments":[{"group":{"start":33,"value":"\"11\"","children":[{"start":34,"value":"11","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"Save and exit report\"","children":[{"start":41,"value":"Save and exit report","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":46,"keywordType":"Action","textWithKeyword":"When I visit the National Referral Mechanism page","stepMatchArguments":[]},{"pwStepLine":83,"gherkinStepLine":47,"keywordType":"Action","textWithKeyword":"And I enter my work Email \"sas-hof-test@digital.homeoffice.gov.uk\" and create new report - check error \"No\"","stepMatchArguments":[{"group":{"start":22,"value":"\"sas-hof-test@digital.homeoffice.gov.uk\"","children":[{"start":23,"value":"sas-hof-test@digital.homeoffice.gov.uk","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":99,"value":"\"No\"","children":[{"start":100,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":84,"gherkinStepLine":48,"keywordType":"Action","textWithKeyword":"And I fill out my answers to some of the NRM questionnaire - check error \"No\"","stepMatchArguments":[{"group":{"start":69,"value":"\"No\"","children":[{"start":70,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":85,"gherkinStepLine":49,"keywordType":"Outcome","textWithKeyword":"Then I click 'Save and exit' button and confirm my report is saved","stepMatchArguments":[]}]},
]; // bdd-data-end