export type SourcePageObjectMap = {
  sourceClass: string;
  refactoredTarget: string;
  rationale: string;
};

// This registry keeps strict traceability from source Java page objects
// to refactored Playwright handlers used in this migration.
export const SOURCE_PAGE_OBJECT_REGISTRY: SourcePageObjectMap[] = [
  { sourceClass: 'NrmHomePage', refactoredTarget: 'NrmStepLib.openNrm', rationale: 'Start page and entry navigation consolidated.' },
  { sourceClass: 'NrmWorkEmailPage', refactoredTarget: 'NrmStepLib.createReport', rationale: 'Email entry and report creation consolidated.' },
  { sourceClass: 'NrmAddReferencePage', refactoredTarget: 'NrmStepLib.answerRefOrganisationAndReportLocationQuestions', rationale: 'Reference section mapped directly.' },
  { sourceClass: 'NrmSelectOrganisationPage', refactoredTarget: 'NrmStepLib.answerRefOrganisationAndReportLocationQuestions', rationale: 'Organisation selection section mapped directly.' },
  { sourceClass: 'NrmWhereAreYouMakingThisReportPage', refactoredTarget: 'NrmStepLib.answerRefOrganisationAndReportLocationQuestions', rationale: 'Report location path preserved.' },
  { sourceClass: 'NrmIsVictimUnder18Page', refactoredTarget: 'NrmStepLib.answerIsTheVictimUnder18', rationale: 'Under-18 branch preserved.' },
  { sourceClass: 'NrmUnder18AnytimeDuringExploitationPage', refactoredTarget: 'NrmStepLib.answerIsTheVictimUnder18', rationale: 'Under-18-at-time branch consolidated.' },
  { sourceClass: 'NrmLocalAuthContactedPage', refactoredTarget: 'NrmStepLib.answerIsTheVictimUnder18', rationale: 'Child-specific local authority branch preserved.' },
  { sourceClass: 'NrmBackgroundPage', refactoredTarget: 'NrmStepLib.answerTheirBackgroundAndExploitationQuestions2', rationale: 'Background narrative fields preserved.' },
  { sourceClass: 'NrmHasThePotentialVictimBeenInMoreThanOneExploitativeSituationPage', refactoredTarget: 'NrmStepLib.answerTheirBackgroundAndExploitationQuestions2', rationale: 'Exploitative situation branch preserved.' },
  { sourceClass: 'NrmWhenDidExploitationHappenPage', refactoredTarget: 'NrmStepLib.answerTheirBackgroundAndExploitationQuestions2', rationale: 'Timeline field preserved.' },
  { sourceClass: 'NrmWhenDidExploitationHappenMultiplePage', refactoredTarget: 'NrmStepLib.answerTheirBackgroundAndExploitationQuestions2', rationale: 'Multiple timeline path consolidated.' },
  { sourceClass: 'NrmHowExploitationStartPage', refactoredTarget: 'NrmStepLib.answerTheirBackgroundAndExploitationQuestions2', rationale: 'How exploitation started field preserved.' },
  { sourceClass: 'NrmWasThePotentialVictimTakenSomewhereByTheirExploitersPage', refactoredTarget: 'NrmStepLib.answerTakenSomewhereByExploiter', rationale: 'Taken-somewhere path preserved.' },
  { sourceClass: 'NrmHowWasThePotentialVictimTreatedDuringTheirExploitationPage', refactoredTarget: 'NrmStepLib.answerTheirTreatmentHowWhyTheyLeftLastContactAndChanceOfReporting', rationale: 'Treatment field preserved.' },
  { sourceClass: 'NrmIsThePotentialVictimStillInAnExploitativeSituationPage', refactoredTarget: 'NrmStepLib.answerTheirTreatmentHowWhyTheyLeftLastContactAndChanceOfReporting', rationale: 'Still-in-situation branch consolidated.' },
  { sourceClass: 'NrmWhatIsKeepingThePotentialVictimInTheSituationPage', refactoredTarget: 'NrmStepLib.answerTheirTreatmentHowWhyTheyLeftLastContactAndChanceOfReporting', rationale: 'In-situation detail preserved.' },
  { sourceClass: 'NrmHowAndWhyTheyLeftPage', refactoredTarget: 'NrmStepLib.answerTheirTreatmentHowWhyTheyLeftLastContactAndChanceOfReporting', rationale: 'Left-situation detail preserved.' },
  { sourceClass: 'NrmWhenWasPotentialVictimAndExploiterLastInContactPage', refactoredTarget: 'NrmStepLib.answerTheirTreatmentHowWhyTheyLeftLastContactAndChanceOfReporting', rationale: 'Last contact timing preserved.' },
  { sourceClass: 'NrmTellUsAboutTheLastContactBetweenThePotentialVictimAndTheirExploitersPage', refactoredTarget: 'NrmStepLib.answerTheirTreatmentHowWhyTheyLeftLastContactAndChanceOfReporting', rationale: 'Last contact details preserved.' },
  { sourceClass: 'NrmFirstTimeOfReportingThisPage', refactoredTarget: 'NrmStepLib.answerTheirTreatmentHowWhyTheyLeftLastContactAndChanceOfReporting', rationale: 'First chance branch consolidated.' },
  { sourceClass: 'NrmWhyAreTheyReportingThisNowPage', refactoredTarget: 'NrmStepLib.answerTheirTreatmentHowWhyTheyLeftLastContactAndChanceOfReporting', rationale: 'Why reporting now field preserved.' },
  { sourceClass: 'NrmTellUsAboutTheInterviewsPage', refactoredTarget: 'NrmStepLib.answerReferralInterviewOtherProfOrgInvolved', rationale: 'Interview details preserved.' },
  { sourceClass: 'NrmAreThereOtherProfessionalsOrOrganisationsInvolvedWithThisCasePage', refactoredTarget: 'NrmStepLib.answerReferralInterviewOtherProfOrgInvolved', rationale: 'Other professionals branch preserved.' },
  { sourceClass: 'NrmOtherProfessionalOrgInvolvedPage', refactoredTarget: 'NrmStepLib.answerReferralInterviewOtherProfOrgInvolved', rationale: 'Organisation details consolidated.' },
  { sourceClass: 'NrmDoYouHaveAnyConcernsAboutThePotentialVictimsCredibilityPage', refactoredTarget: 'NrmStepLib.answerDocEvidenceAndIndicatorsOfDishonestyAndLocationBeingExploited', rationale: 'Credibility indicators preserved.' },
  { sourceClass: 'NrmDidYouIdentifyAnyModernSlaveryIndicatorsPage', refactoredTarget: 'NrmStepLib.answerDocEvidenceAndIndicatorsOfDishonestyAndLocationBeingExploited', rationale: 'Indicators branch consolidated.' },
  { sourceClass: 'NrmTellUsAboutTheDocumentsYouUploadedPage', refactoredTarget: 'NrmStepLib.answerDocEvidenceAndIndicatorsOfDishonestyAndLocationBeingExploited', rationale: 'Document evidence details preserved.' },
  { sourceClass: 'NrmWhereWereTheyExploitedPage', refactoredTarget: 'NrmStepLib.answerDocEvidenceAndIndicatorsOfDishonestyAndLocationBeingExploited', rationale: 'Exploitation location type preserved.' },
  { sourceClass: 'NrmWhereWereTheyExploitedInTheUKPage', refactoredTarget: 'NrmStepLib.answerDocEvidenceAndIndicatorsOfDishonestyAndLocationBeingExploited', rationale: 'UK exploitation details preserved.' },
  { sourceClass: 'NrmWhereWereTheyExploitedOverseasPage', refactoredTarget: 'NrmStepLib.answerDocEvidenceAndIndicatorsOfDishonestyAndLocationBeingExploited', rationale: 'Overseas exploitation details preserved.' },
  { sourceClass: 'NrmWhereIsThePotentialVictimStayingPage', refactoredTarget: 'NrmStepLib.answerWhereAreTheyHowWereTheyExploitedAndOtherPotentialVictims', rationale: 'Current location details preserved.' },
  { sourceClass: 'NrmWhoExploitedThePotentialVictimPage', refactoredTarget: 'NrmStepLib.answerWhereAreTheyHowWereTheyExploitedAndOtherPotentialVictims', rationale: 'Exploiter details preserved.' },
  { sourceClass: 'NrmDoYouHaveInformationAboutWhereTheExploitersArePage', refactoredTarget: 'NrmStepLib.answerWhereAreTheyHowWereTheyExploitedAndOtherPotentialVictims', rationale: 'Exploiters location branch preserved.' },
  { sourceClass: 'NrmAreTheExploitersInTheUKPage', refactoredTarget: 'NrmStepLib.answerWhereAreTheyHowWereTheyExploitedAndOtherPotentialVictims', rationale: 'Exploiters in UK branch preserved.' },
  { sourceClass: 'NrmWhatInfoDoYouHaveAbtExploiterWhereAbtPage', refactoredTarget: 'NrmStepLib.answerWhereAreTheyHowWereTheyExploitedAndOtherPotentialVictims', rationale: 'Exploiters location details preserved.' },
  { sourceClass: 'NrmHowWereTheyExploitedPage', refactoredTarget: 'NrmStepLib.answerWhereAreTheyHowWereTheyExploitedAndOtherPotentialVictims', rationale: 'Exploitation type preserved.' },
  { sourceClass: 'NrmWereThereAnyOtherPotentialVictimsPage', refactoredTarget: 'NrmStepLib.answerWhereAreTheyHowWereTheyExploitedAndOtherPotentialVictims', rationale: 'Other victims branch preserved.' },
  { sourceClass: 'NrmAreThereConcernsThatThePotentialVictimCouldBeExploitedAgainInTheFuturePage', refactoredTarget: 'NrmStepLib.answerWhereAreTheyHowWereTheyExploitedAndOtherPotentialVictims', rationale: 'Future concern branch preserved.' },
  { sourceClass: 'NrmWhyAreThereConcernsAboutExploitationInTheFuturePage', refactoredTarget: 'NrmStepLib.answerWhereAreTheyHowWereTheyExploitedAndOtherPotentialVictims', rationale: 'Future concern details preserved.' },
  { sourceClass: 'NrmDoTheyHaveACrimeReferenceNumberRelatedToAnyReportedModernSlaveryCrimeInWhichTheyAreAVictimPage', refactoredTarget: 'NrmStepLib.answerDoTheyHaveCrimeRefNumbAndCooperationWithPubAuth', rationale: 'Crime reference branch preserved.' },
  { sourceClass: 'NrmCoOperationWithPublicAuthoritiesPage', refactoredTarget: 'NrmStepLib.answerDoTheyHaveCrimeRefNumbAndCooperationWithPubAuth', rationale: 'Cooperation branch preserved.' },
  { sourceClass: 'NrmDoesThePotentialVictimConsentToHavingTheirCaseReferredToTheNrmPage', refactoredTarget: 'NrmStepLib.answerDoTheyWantTheirCaseReferredToNRMAndCompleteQuestionnaire', rationale: 'Referral consent preserved.' },
  { sourceClass: 'NrmDoTheyNeedSupportPage', refactoredTarget: 'NrmStepLib.answerDoTheyWantTheirCaseReferredToNRMAndCompleteQuestionnaire', rationale: 'Support branch preserved.' },
  { sourceClass: 'NrmWhyDontTheyWantTheirCaseReferredPage', refactoredTarget: 'NrmStepLib.answerDoTheyWantTheirCaseReferredToNRMAndCompleteQuestionnaire', rationale: 'No-referral branch preserved.' },
  { sourceClass: 'NrmWhatIsTheNameOfThePotentialVictimPage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'Victim name section preserved.' },
  { sourceClass: 'NrmWhatIsTheirDateOfBirthPage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'DOB section preserved.' },
  { sourceClass: 'NrmWhatIsTheirGenderPage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'Gender section preserved.' },
  { sourceClass: 'NrmDoTheyHaveAnyChildrenPage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'Children section preserved.' },
  { sourceClass: 'NrmSelectNationalityPage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'Nationality section preserved.' },
  { sourceClass: 'NrmDoTheyNeedInterpreterPage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'Interpreter section preserved.' },
  { sourceClass: 'NrmDoTheyNeedHelpWithCommunicationPage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'Communication aid section preserved.' },
  { sourceClass: 'NrmDoTheyHaveAnyHomeOfficeRefPage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'Home Office reference section preserved.' },
  { sourceClass: 'NrmWhoShouldWeSendDecisionToPage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'Decision recipient section preserved.' },
  { sourceClass: 'NrmHowShouldTheyBeContactedPage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'Contact preference section preserved.' },
  { sourceClass: 'NrmCanSupportProviderContactThemByPhonePage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'Phone contact section preserved.' },
  { sourceClass: 'NrmWhatAreYourContactDetailsPage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'FR contact details section preserved.' },
  { sourceClass: 'NrmWhoShouldWeContactInYourAbsencePage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'Alternate contact section preserved.' },
  { sourceClass: 'NrmEvidenceUploadPage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'Upload evidence branch preserved.' },
  { sourceClass: 'NrmCheckYourAnswersPage', refactoredTarget: 'NrmStepLib.uploadEvidenceAndVerifyCheckYourAnswer', rationale: 'Check answers consolidation.' },
  { sourceClass: 'NrmSentConfirmationPage', refactoredTarget: 'NrmStepLib.confirmSubmission', rationale: 'Submission confirmation preserved.' },
  { sourceClass: 'NrmContinueToYourReportPage', refactoredTarget: 'NrmStepLib.createReport', rationale: 'Start/continue report handling consolidated.' },
  { sourceClass: 'NrmDraftReportsPage', refactoredTarget: 'NrmStepLib.continuingReport/deleteReport', rationale: 'Draft report actions preserved.' },
  { sourceClass: 'NrmCurrentProgressPage', refactoredTarget: 'NrmStepLib.continuingReport', rationale: 'Continue journey action preserved.' },
  { sourceClass: 'NrmDeleteReportPage', refactoredTarget: 'NrmStepLib.deleteReport', rationale: 'Delete confirmation preserved.' },
  { sourceClass: 'NrmYourReportHasBeenSavedPage', refactoredTarget: 'NrmStepLib.isReportSaved', rationale: 'Save and exit confirmation preserved.' }
];
