apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-govuk
  namespace: ms-prod
{{ file .INGRESS_EXTERNAL_ANNOTATIONS | indent 2 }}
spec:
  rules:
  - host: www.modernslavery.gov.uk
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 10443
        path: /
  tls:
  - hosts:
    - www.modernslavery.gov.uk
    secretName: cert-govuk-cmio
