{
 "title": "Modern Slavery",
 "tags": [
  "Sysdig",
  "Private dashboard"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Incomplete Forms (Save and Return)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"id\"\nFROM reports\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "NRM Form ➡️ SQS Error ❌",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n $__timeGroupAlias(created_at,$__interval),\n count(id) AS \"id\"\nFROM hof\nWHERE\n $__timeFilter(created_at) AND\n success = 'false'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "NRM Form ➡️ SQS ✅",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n $__timeGroupAlias(created_at,$__interval),\n count(id) AS \"id\"\nFROM hof\nWHERE\n $__timeFilter(created_at) AND\n success = 'true'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Resolver ➡️ iCasework Submission Failed ❌",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n $__timeGroupAlias(created_at,$__interval),\n count(id) AS \"id\"\nFROM resolver\nWHERE\n $__timeFilter(created_at) AND\n success = 'false'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Resolver ➡️ iCasework Submission ✅",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n $__timeGroupAlias(created_at,$__interval),\n count(id) AS \"id\"\nFROM resolver\nWHERE\n $__timeFilter(created_at) AND\n success = 'true'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DTN Submissions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n $__timeGroupAlias(created_at,$__interval),\n count(id) AS \"id\"\nFROM hof\nWHERE\n $__timeFilter(created_at) AND\n type = '662265' AND\n success = 'true'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "NRM Submissions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n $__timeGroupAlias(created_at,$__interval),\n count(id) AS \"id\"\nFROM hof\nWHERE\n $__timeFilter(created_at) AND\n type = '560734' AND\n success = 'true'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of SQS Messages Recieved",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "filter": "cloudProvider.id=\"ms-sqs\"",
     "groupAggregation": "sum",
     "sortDirection": "desc",
     "target": "aws.sqs.NumberOfMessagesReceived",
     "timeAggregation": "sum"
    }
   ]
  },
  {
   "title": "Duplicates",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"id\"\nFROM duplicates\nWHERE\n  $__timeFilter(created_at) AND\n  duplicate = 'true'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of message in Dead Letter Queue 😵",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Total cases in queue" }
   ],
   "targets": [
    {
     "filter": "cloudProvider.id=\"ms-sqs-dlq\"",
     "groupAggregation": "max",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "aws.sqs.ApproximateNumberOfMessagesVisible",
     "timeAggregation": "max"
    }
   ]
  }
 ]
}